// core-include;
#include citizen.pwn
#include tutorial.pwn
#include tutorial_list.pwn
#include interiors.pwn
#include backpack.pwn // promijenjeno iz backpack.pwn u backpackNew.pwn // vraceno nazad zbog buga koji su dozviljavali neki igraci
#include items.pwn
#include real_estate.pwn // test
#include land.pwn
#include time.pwn
#include hunger.pwn
#include chat.pwn
#include explosive.pwn
#include loginNew.pwn
#include registracija.pwn

#include _vehicles

#include exchange.pwn
#include furniture.pwn
#include prijave.pwn
#include advertisements.pwn
//#include rnl.pwn
#include panel.pwn
#include atm.pwn
#include bank.pwn
//#include veh_rent.pwn // additional
#include mobitel.pwn
//#include phone.pwn
#include pm.pwn
#include gps.pwn
#include weather.pwn
#include ucp.pwn
#include payday.pwn
#include aktivna_igra.pwn
#include tuning.pwn
#include autoskola.pwn
#include death_list.pwn // additional
#include granice.pwn
#include lottery.pwn
#include diler_oruzja.pwn
#include burglary.pwn
#include permissions\vip.pwn
//#include paketici.pwn
#include accessories.pwn
#include prostitutes.pwn
#include admin_notes.pwn
#include referral.pwn
#include noviigrac.pwn
//#include discord.pwn
#include serverekonomija.pwn
#include shooting_range.pwn
#include servis.pwn
//#include winter.pwn
//#include snowball.pwn
//#include zatvor_area_posao.pwn
