
new  	
    mysql_upit[512],          
	string_32[32],          
    string_64[64], 			
    string_128[128],	
	string_256[256],
    bool:actorHandsUp[200 char],
    gChatCleared,
	ucitavanje_pocetak,
	serverRegistracijeZakljucane = 0,
    zona_area51,
    djMusicLink[150],
    bool:TurfState[MAX_PLAYERS] = false,
    bool:TDSelected[MAX_PLAYERS char] = false,
	antispam[MAX_PLAYERS],                 
    antispam_vreme[MAX_PLAYERS],
	transfer_id[MAX_PLAYERS],              
    transfer_iznos[MAX_PLAYERS],
	transfer_od[MAX_PLAYERS],
	gJoinTimestamp[MAX_PLAYERS],               
	gLoginTimestampLimit[MAX_PLAYERS],         
    gRegTimestampLimit[MAX_PLAYERS],
	gHospitalBill[MAX_PLAYERS],                        
	firma_kupuje[MAX_PLAYERS],
	Float:pozicija[MAX_PLAYERS][4],        
	pVehicles[MAX_PLAYERS][6], // 6 slotova za vozila; ako se menja, promeniti i exchange.pwn
    pRealEstate[MAX_PLAYERS][6], //
    pAttachedObjects[MAX_PLAYERS][10],
    cur_wep[MAX_PLAYERS],                   
	cinc[MAX_PLAYERS],                      
	novac_izmenjen[MAX_PLAYERS],			
	picked_pickup[MAX_PLAYERS], 			
	Float:km_pos[MAX_PLAYERS][3],			
    Float:kilometraza[MAX_PLAYERS], // u metrima, ne u kilometrima!
    koristio_chat[MAX_PLAYERS],	
    bool:pAdminMusic[MAX_PLAYERS char],
    bool:pRestoreData[MAX_PLAYERS char],
    bool:gAnimationsPreloaded[MAX_PLAYERS char],		
	bool:transfer_ponudjen[MAX_PLAYERS char],
    bool:zamrznut[MAX_PLAYERS char],
	bool:hPM[MAX_PLAYERS char],
	bool:IgracevCPPrikazan[MAX_PLAYERS char],   
    bool:IgracevRCPPrikazan[MAX_PLAYERS char],
	bool:gPlayerReversing[MAX_PLAYERS char],           
	bool:gPlayerSpawned[MAX_PLAYERS char],
	bool:driveby[MAX_PLAYERS char],				
	bool:gCrashSpawn[MAX_PLAYERS char],			
    tajmer:NovacTD[MAX_PLAYERS],
	tajmer:kick[MAX_PLAYERS],		
    tmrIntroCam,            
    ime_obicno[MAX_PLAYERS][MAX_PLAYER_NAME],
    ime_rp[MAX_PLAYERS][MAX_PLAYER_NAME],
    Text3D:pText3D[MAX_PLAYERS],
    Iterator:iPlayersConnecting<MAX_PLAYERS>,
	Regex:regex_ime,
    Regex:regex_spec_ime,
	Regex:regex_email,
    Float:gIntroCamAngle,
    bool:testingdaddy;