    tdAnimHelp = TextDrawCreate(610.0, 400.0, "~b~~k~~PED_LOCK_TARGET~ ~w~da zaustavite animaciju.");
    TextDrawLetterSize(tdAnimHelp, 0.269666, 1.334518);
    TextDrawUseBox(tdAnimHelp, 0);
    TextDrawFont(tdAnimHelp, 2);
    TextDrawSetShadow(tdAnimHelp, 0);
    TextDrawSetOutline(tdAnimHelp, 1);
    TextDrawBackgroundColor(tdAnimHelp, 0x000000FF);
    TextDrawColor(tdAnimHelp, 0xFFFFFFFF);
    TextDrawAlignment(tdAnimHelp, 3);