    tdBottomOld[0] = TextDrawCreate(661.000000, 429.000000, "_"); //16
    TextDrawBackgroundColor(tdBottomOld[0], 255);
    TextDrawFont(tdBottomOld[0], 1);
    TextDrawLetterSize(tdBottomOld[0], 0.500000, 2.000000);
    TextDrawColor(tdBottomOld[0], -1);
    TextDrawSetOutline(tdBottomOld[0], 0);
    TextDrawSetProportional(tdBottomOld[0], 1);
    TextDrawSetShadow(tdBottomOld[0], 1);
    TextDrawUseBox(tdBottomOld[0], 1);
    TextDrawBoxColor(tdBottomOld[0], 150);
    TextDrawTextSize(tdBottomOld[0], -50.000000, 0.000000);

    tdBottomOld[1] = TextDrawCreate(4.000000, 433.000000, "~b~~h~OGLAS: ~W~Prazno. da date oglas koristite /oglas."); //18
    TextDrawBackgroundColor(tdBottomOld[1], 255);
    TextDrawFont(tdBottomOld[1], 2);
    TextDrawLetterSize(tdBottomOld[1], 0.200000, 1.000000);
    TextDrawColor(tdBottomOld[1], -1);
    TextDrawSetOutline(tdBottomOld[1], 0);
    TextDrawSetProportional(tdBottomOld[1], 1);
    TextDrawSetShadow(tdBottomOld[1], 1);