    // Deo sa random porukama (tips)
    // ----------------------------------------------------------------------------------
    tdTips[0] = TextDrawCreate(198.971343, 418.033599, "ld_beat:chit");
    TextDrawTextSize(tdTips[0], -33.000000, 28.000000);
    TextDrawAlignment(tdTips[0], 1);
    TextDrawColor(tdTips[0], 7448319);
    TextDrawSetShadow(tdTips[0], 0);
    TextDrawBackgroundColor(tdTips[0], 255);
    TextDrawFont(tdTips[0], 4);
    TextDrawSetProportional(tdTips[0], 0);

    tdTips[1] = TextDrawCreate(199.771392, 418.033599, "ld_beat:chit");
    TextDrawTextSize(tdTips[1], -33.000000, 28.000000);
    TextDrawAlignment(tdTips[1], 1);
    TextDrawColor(tdTips[1], 255);
    TextDrawSetShadow(tdTips[1], 0);
    TextDrawBackgroundColor(tdTips[1], 255);
    TextDrawFont(tdTips[1], 4);
    TextDrawSetProportional(tdTips[1], 0);

    tdTips[2] = TextDrawCreate(471.644042, 418.166778, "ld_beat:chit");
    TextDrawTextSize(tdTips[2], -33.000000, 28.000000);
    TextDrawAlignment(tdTips[2], 1);
    TextDrawColor(tdTips[2], 7448319);
    TextDrawSetShadow(tdTips[2], 0);
    TextDrawBackgroundColor(tdTips[2], 255);
    TextDrawFont(tdTips[2], 4);
    TextDrawSetProportional(tdTips[2], 0);

    tdTips[3] = TextDrawCreate(470.944000, 418.166778, "ld_beat:chit");
    TextDrawTextSize(tdTips[3], -33.000000, 28.000000);
    TextDrawAlignment(tdTips[3], 1);
    TextDrawColor(tdTips[3], 255);
    TextDrawSetShadow(tdTips[3], 0);
    TextDrawBackgroundColor(tdTips[3], 255);
    TextDrawFont(tdTips[3], 4);
    TextDrawSetProportional(tdTips[3], 0);

    // tdTips[4] = TextDrawCreate(319.796325, 425.167236, "box");
    // TextDrawLetterSize(tdTips[4], 0.000000, 1.546965);
    // TextDrawTextSize(tdTips[4], 0.000000, 266.000000);
    // TextDrawAlignment(tdTips[4], 2);
    // TextDrawColor(tdTips[4], -1);
    // TextDrawUseBox(tdTips[4], 1);
    // TextDrawBoxColor(tdTips[4], 255);
    // TextDrawSetShadow(tdTips[4], 0);
    // TextDrawBackgroundColor(tdTips[4], 255);
    // TextDrawFont(tdTips[4], 1);
    // TextDrawSetProportional(tdTips[4], 1);

    tdTips[4] = TextDrawCreate(183.400375, 422.555633, "LD_SPAC:white");
    TextDrawTextSize(tdTips[4], 271.000000, 18.979999);
    TextDrawAlignment(tdTips[4], 1);
    TextDrawColor(tdTips[4], 255);
    TextDrawSetShadow(tdTips[4], 0);
    TextDrawBackgroundColor(tdTips[4], 255);
    TextDrawFont(tdTips[4], 4);
    TextDrawSetProportional(tdTips[4], 0);

    tdTips[5] = TextDrawCreate(167.951629, 432.167297, "particle:lamp_shad_64");
    TextDrawTextSize(tdTips[5], 319.000000, 9.000000);
    TextDrawAlignment(tdTips[5], 1);
    TextDrawColor(tdTips[5], 7448128);
    TextDrawSetShadow(tdTips[5], 0);
    TextDrawBackgroundColor(tdTips[5], 255);
    TextDrawFont(tdTips[5], 4);
    TextDrawSetProportional(tdTips[5], 0);

    tdTips[6] = TextDrawCreate(319.943054, 428.666717, "_"); // Tekst poruke
    TextDrawLetterSize(tdTips[6], 0.142202, 0.809997);
    TextDrawTextSize(tdTips[6], 0.000000, 273.000000);
    TextDrawAlignment(tdTips[6], 2);
    TextDrawColor(tdTips[6], -1);
    TextDrawSetShadow(tdTips[6], 0);
    TextDrawSetOutline(tdTips[6], 1);
    TextDrawBackgroundColor(tdTips[6], 255);
    TextDrawFont(tdTips[6], 1);
    TextDrawSetProportional(tdTips[6], 1);


    // Happy Hours
    // ----------------------------------------------------------------------------------
    tdHappyHours[0] = TextDrawCreate(3.610352, 387.050048, "LD_BEAT:CHIT");
    TextDrawTextSize(tdHappyHours[0], 27.000000, 30.000000);
    TextDrawAlignment(tdHappyHours[0], 1);
    TextDrawColor(tdHappyHours[0], 255);
    TextDrawSetShadow(tdHappyHours[0], 0);
    TextDrawBackgroundColor(tdHappyHours[0], 255);
    TextDrawFont(tdHappyHours[0], 4);
    TextDrawSetProportional(tdHappyHours[0], 0);

    tdHappyHours[1] = TextDrawCreate(6.110465, 389.850219, "LD_BEAT:CHIT");
    TextDrawTextSize(tdHappyHours[1], 22.000000, 24.500000);
    TextDrawAlignment(tdHappyHours[1], 1);
    TextDrawColor(tdHappyHours[1], -16776961);
    TextDrawSetShadow(tdHappyHours[1], 0);
    TextDrawBackgroundColor(tdHappyHours[1], 255);
    TextDrawFont(tdHappyHours[1], 4);
    TextDrawSetProportional(tdHappyHours[1], 0);

    tdHappyHours[2] = TextDrawCreate(7.210556, 389.866912, "LD_BEAT:CHIT");
    TextDrawTextSize(tdHappyHours[2], 20.000000, 24.000000);
    TextDrawAlignment(tdHappyHours[2], 1);
    TextDrawColor(tdHappyHours[2], 255);
    TextDrawSetShadow(tdHappyHours[2], 0);
    TextDrawBackgroundColor(tdHappyHours[2], 255);
    TextDrawFont(tdHappyHours[2], 4);
    TextDrawSetProportional(tdHappyHours[2], 0);

    tdHappyHours[3] = TextDrawCreate(16.875104, 397.316925, "HH");
    TextDrawLetterSize(tdHappyHours[3], 0.224773, 1.035830);
    TextDrawTextSize(tdHappyHours[3], 0.000000, 320.000000);
    TextDrawAlignment(tdHappyHours[3], 2);
    TextDrawColor(tdHappyHours[3], -1);
    TextDrawSetShadow(tdHappyHours[3], 0);
    TextDrawBackgroundColor(tdHappyHours[3], 255);
    TextDrawFont(tdHappyHours[3], 1);
    TextDrawSetProportional(tdHappyHours[3], 1);


    // Happy Job
    // ----------------------------------------------------------------------------------
    tdHappyJob[0] = TextDrawCreate(3.610352, 417.050048, "LD_BEAT:CHIT");
    TextDrawTextSize(tdHappyJob[0], 27.000000, 30.000000);
    TextDrawAlignment(tdHappyJob[0], 1);
    TextDrawColor(tdHappyJob[0], 255);
    TextDrawSetShadow(tdHappyJob[0], 0);
    TextDrawBackgroundColor(tdHappyJob[0], 255);
    TextDrawFont(tdHappyJob[0], 4);
    TextDrawSetProportional(tdHappyJob[0], 0);

    tdHappyJob[1] = TextDrawCreate(6.110465, 419.850219, "LD_BEAT:CHIT");
    TextDrawTextSize(tdHappyJob[1], 22.000000, 24.500000);
    TextDrawAlignment(tdHappyJob[1], 1);
    TextDrawColor(tdHappyJob[1], -16776961);
    // TextDrawColor(tdHappyJob[1], 8388863);
    TextDrawSetShadow(tdHappyJob[1], 0);
    TextDrawBackgroundColor(tdHappyJob[1], 255);
    TextDrawFont(tdHappyJob[1], 4);
    TextDrawSetProportional(tdHappyJob[1], 0);

    tdHappyJob[2] = TextDrawCreate(7.210556, 419.866912, "LD_BEAT:CHIT");
    TextDrawTextSize(tdHappyJob[2], 20.000000, 24.000000);
    TextDrawAlignment(tdHappyJob[2], 1);
    TextDrawColor(tdHappyJob[2], 255);
    TextDrawSetShadow(tdHappyJob[2], 0);
    TextDrawBackgroundColor(tdHappyJob[2], 255);
    TextDrawFont(tdHappyJob[2], 4);
    TextDrawSetProportional(tdHappyJob[2], 0);

    tdHappyJob[3] = TextDrawCreate(16.875104, 427.316925, "HJ");
    TextDrawLetterSize(tdHappyJob[3], 0.224773, 1.035830);
    TextDrawTextSize(tdHappyJob[3], 0.000000, 320.000000);
    TextDrawAlignment(tdHappyJob[3], 2);
    TextDrawColor(tdHappyJob[3], -1);
    TextDrawSetShadow(tdHappyJob[3], 0);
    TextDrawBackgroundColor(tdHappyJob[3], 255);
    TextDrawFont(tdHappyJob[3], 1);
    TextDrawSetProportional(tdHappyJob[3], 1);

    // tdHappyJob[4] = TextDrawCreate(64.376441, 424.149841, "LD_BEAT:CHIT");
    // TextDrawTextSize(tdHappyJob[4], -20.000000, 15.659992);
    // TextDrawAlignment(tdHappyJob[4], 1);
    // TextDrawColor(tdHappyJob[4], 255);
    // TextDrawSetShadow(tdHappyJob[4], 0);
    // TextDrawBackgroundColor(tdHappyJob[4], 255);
    // TextDrawFont(tdHappyJob[4], 4);
    // TextDrawSetProportional(tdHappyJob[4], 0);

    tdHappyJob[4] = TextDrawCreate(73.376457, 424.535064, "LD_BEAT:CHIT");
    TextDrawTextSize(tdHappyJob[4], -20.000000, 15.649999);
    TextDrawAlignment(tdHappyJob[4], 1);
    TextDrawColor(tdHappyJob[4], 255);
    TextDrawSetShadow(tdHappyJob[4], 0);
    TextDrawBackgroundColor(tdHappyJob[4], 255);
    TextDrawFont(tdHappyJob[4], 4);
    TextDrawSetProportional(tdHappyJob[4], 0);

    tdHappyJob[5] = TextDrawCreate(24.298822, 426.933349, "LD_SPAC:white");
    TextDrawTextSize(tdHappyJob[5], 40.500000, 10.590012);
    TextDrawAlignment(tdHappyJob[5], 1);
    TextDrawColor(tdHappyJob[5], 255);
    TextDrawSetShadow(tdHappyJob[5], 0);
    TextDrawBackgroundColor(tdHappyJob[5], 255);
    TextDrawFont(tdHappyJob[5], 4);
    TextDrawSetProportional(tdHappyJob[5], 0);


    // tdHappyJob[5] = TextDrawCreate(27.028141, 429.066528, "_");
    // TextDrawLetterSize(tdHappyJob[5], 0.142285, 0.664999);
    // TextDrawTextSize(tdHappyJob[5], 53.400009, 0.000000);
    // TextDrawAlignment(tdHappyJob[5], 1);
    // TextDrawColor(tdHappyJob[5], -1);
    // TextDrawUseBox(tdHappyJob[5], 1);
    // TextDrawBoxColor(tdHappyJob[5], 255);
    // TextDrawSetShadow(tdHappyJob[5], 0);
    // TextDrawSetOutline(tdHappyJob[5], -1);
    // TextDrawBackgroundColor(tdHappyJob[5], 255);
    // TextDrawFont(tdHappyJob[5], 2);
    // TextDrawSetProportional(tdHappyJob[5], 1);

    tdHappyJob[6] = TextDrawCreate(26.961465, 428.881286, "_");
    TextDrawLetterSize(tdHappyJob[6], 0.142285, 0.664999);
    TextDrawTextSize(tdHappyJob[6], 53.000000, 0.549998);
    TextDrawAlignment(tdHappyJob[6], 1);
    TextDrawColor(tdHappyJob[6], -1);
    TextDrawSetShadow(tdHappyJob[6], 0);
    TextDrawSetOutline(tdHappyJob[6], -1);
    TextDrawBackgroundColor(tdHappyJob[6], 255);
    TextDrawFont(tdHappyJob[6], 2);
    TextDrawSetProportional(tdHappyJob[6], 1);


    // Broj igraca
    // ----------------------------------------------------------------------------------
    tdPlayerCount[0] = TextDrawCreate(610.705993, 417.450073, "LD_BEAT:CHIT");
    TextDrawTextSize(tdPlayerCount[0], 27.000000, 30.000000);
    TextDrawAlignment(tdPlayerCount[0], 1);
    TextDrawColor(tdPlayerCount[0], 255);
    TextDrawSetShadow(tdPlayerCount[0], 0);
    TextDrawBackgroundColor(tdPlayerCount[0], 255);
    TextDrawFont(tdPlayerCount[0], 4);
    TextDrawSetProportional(tdPlayerCount[0], 0);

    tdPlayerCount[1] = TextDrawCreate(613.206115, 420.250244, "LD_BEAT:CHIT");
    TextDrawTextSize(tdPlayerCount[1], 22.000000, 24.500000);
    TextDrawAlignment(tdPlayerCount[1], 1);
    TextDrawColor(tdPlayerCount[1], 7448319);
    TextDrawSetShadow(tdPlayerCount[1], 0);
    TextDrawBackgroundColor(tdPlayerCount[1], 255);
    TextDrawFont(tdPlayerCount[1], 4);
    TextDrawSetProportional(tdPlayerCount[1], 0);

    tdPlayerCount[2] = TextDrawCreate(614.306213, 420.266937, "LD_BEAT:CHIT");
    TextDrawTextSize(tdPlayerCount[2], 20.000000, 24.000000);
    TextDrawAlignment(tdPlayerCount[2], 1);
    TextDrawColor(tdPlayerCount[2], 255);
    TextDrawSetShadow(tdPlayerCount[2], 0);
    TextDrawBackgroundColor(tdPlayerCount[2], 255);
    TextDrawFont(tdPlayerCount[2], 4);
    TextDrawSetProportional(tdPlayerCount[2], 0);

    tdPlayerCount[3] = TextDrawCreate(624.370849, 426.916900, "_");
    TextDrawLetterSize(tdPlayerCount[3], 0.173234, 1.152495);
    TextDrawTextSize(tdPlayerCount[3], 0.000000, 320.000000);
    TextDrawAlignment(tdPlayerCount[3], 2);
    TextDrawColor(tdPlayerCount[3], -1);
    TextDrawSetShadow(tdPlayerCount[3], 0);
    TextDrawBackgroundColor(tdPlayerCount[3], 255);
    TextDrawFont(tdPlayerCount[3], 2);
    TextDrawSetProportional(tdPlayerCount[3], 1);


    // Sat/vreme
    // ----------------------------------------------------------------------------------
    tdClock[0] = TextDrawCreate(587.700561, 424.700408, "LD_BEAT:CHIT");
    TextDrawTextSize(tdClock[0], -20.000000, 16.000000);
    TextDrawAlignment(tdClock[0], 1);
    TextDrawColor(tdClock[0], 255);
    TextDrawSetShadow(tdClock[0], 0);
    TextDrawBackgroundColor(tdClock[0], 255);
    TextDrawFont(tdClock[0], 4);
    TextDrawSetProportional(tdClock[0], 0);

    // tdClock[1] = TextDrawCreate(579.827697, 429.433868, "box");
    // TextDrawLetterSize(tdClock[1], 0.000000, 0.650429);
    // TextDrawTextSize(tdClock[1], 615.000000, 0.000000);
    // TextDrawAlignment(tdClock[1], 1);
    // TextDrawColor(tdClock[1], -1);
    // TextDrawUseBox(tdClock[1], 1);
    // TextDrawBoxColor(tdClock[1], 255);
    // TextDrawSetShadow(tdClock[1], 0);
    // TextDrawBackgroundColor(tdClock[1], 255);
    // TextDrawFont(tdClock[1], 1);
    // TextDrawSetProportional(tdClock[1], 1);

    tdClock[1] = TextDrawCreate(576.598876, 427.418518, "LD_SPAC:white");
    TextDrawTextSize(tdClock[1], 40.500000, 10.590013);
    TextDrawAlignment(tdClock[1], 1);
    TextDrawColor(tdClock[1], 255);
    TextDrawSetShadow(tdClock[1], 0);
    TextDrawBackgroundColor(tdClock[1], 255);
    TextDrawFont(tdClock[1], 4);
    TextDrawSetProportional(tdClock[1], 0);

    tdClock[2] = TextDrawCreate(595.862243, 427.233642, "--:--");
    TextDrawLetterSize(tdClock[2], 0.133561, 0.971660);
    TextDrawTextSize(tdClock[2], 0.059999, 665.000000);
    TextDrawAlignment(tdClock[2], 2);
    TextDrawColor(tdClock[2], -1);
    TextDrawSetShadow(tdClock[2], 0);
    TextDrawBackgroundColor(tdClock[2], 255);
    TextDrawFont(tdClock[2], 2);
    TextDrawSetProportional(tdClock[2], 1);