    tdDMFirstBlood = TextDrawCreate(322.500488, 102.059257, "FIRST BLOOD");
    TextDrawLetterSize(tdDMFirstBlood, 0.670665, 2.460367);
    TextDrawTextSize(tdDMFirstBlood, 0.000000, 254.000000);
    TextDrawAlignment(tdDMFirstBlood, 2);
    TextDrawColor(tdDMFirstBlood, 16711935);
    TextDrawSetShadow(tdDMFirstBlood, 0);
    TextDrawSetOutline(tdDMFirstBlood, 3);
    TextDrawBackgroundColor(tdDMFirstBlood, 255);
    TextDrawFont(tdDMFirstBlood, 3);
    TextDrawSetProportional(tdDMFirstBlood, 1);

    tdDMDouble = TextDrawCreate(322.500488, 102.059257, "Double kill");
    TextDrawLetterSize(tdDMDouble, 0.670665, 2.460367);
    TextDrawTextSize(tdDMDouble, 0.000000, 254.000000);
    TextDrawAlignment(tdDMDouble, 2);
    TextDrawColor(tdDMDouble, -65281);
    TextDrawSetShadow(tdDMDouble, 0);
    TextDrawSetOutline(tdDMDouble, 3);
    TextDrawBackgroundColor(tdDMDouble, 255);
    TextDrawFont(tdDMDouble, 3);
    TextDrawSetProportional(tdDMDouble, 1);

    tdDMTriple = TextDrawCreate(322.500488, 102.059257, "Triple kill");
    TextDrawLetterSize(tdDMTriple, 0.670665, 2.460367);
    TextDrawTextSize(tdDMTriple, 0.000000, 254.000000);
    TextDrawAlignment(tdDMTriple, 2);
    TextDrawColor(tdDMTriple, -5963521);
    TextDrawSetShadow(tdDMTriple, 0);
    TextDrawSetOutline(tdDMTriple, 3);
    TextDrawBackgroundColor(tdDMTriple, 255);
    TextDrawFont(tdDMTriple, 3);
    TextDrawSetProportional(tdDMTriple, 1);

    tdDMQuad = TextDrawCreate(322.500488, 102.059257, "Quadriple kill");
    TextDrawLetterSize(tdDMQuad, 0.670665, 2.460367);
    TextDrawTextSize(tdDMQuad, 0.000000, 254.000000);
    TextDrawAlignment(tdDMQuad, 2);
    TextDrawColor(tdDMQuad, -16711681);
    TextDrawSetShadow(tdDMQuad, 0);
    TextDrawSetOutline(tdDMQuad, 3);
    TextDrawBackgroundColor(tdDMQuad, 255);
    TextDrawFont(tdDMQuad, 3);
    TextDrawSetProportional(tdDMQuad, 1);

    tdDMPenta = TextDrawCreate(322.500488, 102.059257, "!!! penta kill !!!");
    TextDrawLetterSize(tdDMPenta, 0.670665, 2.460367);
    TextDrawTextSize(tdDMPenta, 0.000000, 254.000000);
    TextDrawAlignment(tdDMPenta, 2);
    TextDrawColor(tdDMPenta, -16776961);
    TextDrawSetShadow(tdDMPenta, 0);
    TextDrawSetOutline(tdDMPenta, 3);
    TextDrawBackgroundColor(tdDMPenta, 255);
    TextDrawFont(tdDMPenta, 3);
    TextDrawSetProportional(tdDMPenta, 1);

    // --------------------------------------------------------------------

    tdDMEvent[0] = TextDrawCreate(251.333251, 386.688293, "box");
    TextDrawLetterSize(tdDMEvent[0], 0.000000, 4.311342);
    TextDrawTextSize(tdDMEvent[0], 380.000000, 0.000000);
    TextDrawAlignment(tdDMEvent[0], 1);
    TextDrawColor(tdDMEvent[0], -114);
    TextDrawUseBox(tdDMEvent[0], 1);
    TextDrawBoxColor(tdDMEvent[0], 176);
    TextDrawSetShadow(tdDMEvent[0], 0);
    TextDrawBackgroundColor(tdDMEvent[0], 255);
    TextDrawFont(tdDMEvent[0], 1);
    TextDrawSetProportional(tdDMEvent[0], 1);

    tdDMEvent[1] = TextDrawCreate(253.999954, 373.703033, "DM Event");
    TextDrawLetterSize(tdDMEvent[1], 0.400000, 1.600000);
    TextDrawTextSize(tdDMEvent[1], 378.000000, 0.000000);
    TextDrawAlignment(tdDMEvent[1], 1);
    TextDrawColor(tdDMEvent[1], -1);
    TextDrawSetShadow(tdDMEvent[1], 0);
    TextDrawSetOutline(tdDMEvent[1], 1);
    TextDrawBackgroundColor(tdDMEvent[1], 255);
    TextDrawFont(tdDMEvent[1], 0);
    TextDrawSetProportional(tdDMEvent[1], 1);

    tdDMEvent[2] = TextDrawCreate(254.699234, 394.028900, "TEAM A - 0~N~~N~0");
    TextDrawLetterSize(tdDMEvent[2], 0.192999, 1.006814);
    TextDrawTextSize(tdDMEvent[2], 318.000000, 0.000000);
    TextDrawAlignment(tdDMEvent[2], 1);
    TextDrawColor(tdDMEvent[2], -16776961);
    TextDrawSetShadow(tdDMEvent[2], 0);
    TextDrawSetOutline(tdDMEvent[2], 1);
    TextDrawBackgroundColor(tdDMEvent[2], 255);
    TextDrawFont(tdDMEvent[2], 2);
    TextDrawSetProportional(tdDMEvent[2], 1);

    tdDMEvent[3] = TextDrawCreate(375.200408, 394.028900, "0 - TEAM B~N~~N~0");
    TextDrawLetterSize(tdDMEvent[3], 0.192999, 1.006814);
    TextDrawTextSize(tdDMEvent[3], 158.000000, 0.000000);
    TextDrawAlignment(tdDMEvent[3], 3);
    TextDrawColor(tdDMEvent[3], -2139062017);
    TextDrawSetShadow(tdDMEvent[3], 0);
    TextDrawSetOutline(tdDMEvent[3], 1);
    TextDrawBackgroundColor(tdDMEvent[3], 255);
    TextDrawFont(tdDMEvent[3], 2);
    TextDrawSetProportional(tdDMEvent[3], 1);

    tdDMEvent[4] = TextDrawCreate(494.800292, 178.987411, "VREME:      --:--");
    TextDrawLetterSize(tdDMEvent[4], 0.319332, 1.776666);
    TextDrawTextSize(tdDMEvent[4], 638.000000, 0.000000);
    TextDrawAlignment(tdDMEvent[4], 1);
    TextDrawColor(tdDMEvent[4], -1580072961);
    TextDrawSetShadow(tdDMEvent[4], 0);
    TextDrawSetOutline(tdDMEvent[4], 1);
    TextDrawBackgroundColor(tdDMEvent[4], 255);
    TextDrawFont(tdDMEvent[4], 2);
    TextDrawSetProportional(tdDMEvent[4], 1);

    tdDMEvent[5] = TextDrawCreate(321.400573, 126.285087, "_");
    TextDrawLetterSize(tdDMEvent[5], 0.353332, 2.035556);
    TextDrawTextSize(tdDMEvent[5], 0.000000, 296.000000);
    TextDrawAlignment(tdDMEvent[5], 2);
    TextDrawColor(tdDMEvent[5], -2139062017);
    TextDrawSetShadow(tdDMEvent[5], 0);
    TextDrawSetOutline(tdDMEvent[5], 1);
    TextDrawBackgroundColor(tdDMEvent[5], 255);
    TextDrawFont(tdDMEvent[5], 2);
    TextDrawSetProportional(tdDMEvent[5], 1);