	tdFactionSafe[0] = TextDrawCreate(155.834579, 180.083374, "LD_SPAC:white");
	TextDrawTextSize(tdFactionSafe[0], 330.000000, 165.000000);
	TextDrawAlignment(tdFactionSafe[0], 1);
	TextDrawColor(tdFactionSafe[0], 170);
	TextDrawSetShadow(tdFactionSafe[0], 0);
	TextDrawBackgroundColor(tdFactionSafe[0], 255);
	TextDrawFont(tdFactionSafe[0], 4);
	TextDrawSetProportional(tdFactionSafe[0], 0);

	tdFactionSafe[1] = TextDrawCreate(162.393875, 187.083343, "LD_SPAC:white");
	TextDrawTextSize(tdFactionSafe[1], 316.000000, 151.000000);
	TextDrawAlignment(tdFactionSafe[1], 1);
	TextDrawColor(tdFactionSafe[1], -2139062152);
	TextDrawSetShadow(tdFactionSafe[1], 0);
	TextDrawBackgroundColor(tdFactionSafe[1], 255);
	TextDrawFont(tdFactionSafe[1], 4);
	TextDrawSetProportional(tdFactionSafe[1], 0);

	tdFactionSafe[2] = TextDrawCreate(169.996093, 236.499938, "LD_SPAC:white");
	TextDrawTextSize(tdFactionSafe[2], 68.000000, 67.000000);
	TextDrawAlignment(tdFactionSafe[2], 1);
	TextDrawColor(tdFactionSafe[2], 170);
	TextDrawSetShadow(tdFactionSafe[2], 0);
	TextDrawBackgroundColor(tdFactionSafe[2], 255);
	TextDrawFont(tdFactionSafe[2], 4);
	TextDrawSetProportional(tdFactionSafe[2], 0);

	tdFactionSafe[3] = TextDrawCreate(247.496002, 236.499938, "LD_SPAC:white");
	TextDrawTextSize(tdFactionSafe[3], 68.000000, 67.000000);
	TextDrawAlignment(tdFactionSafe[3], 1);
	TextDrawColor(tdFactionSafe[3], 170);
	TextDrawSetShadow(tdFactionSafe[3], 0);
	TextDrawBackgroundColor(tdFactionSafe[3], 255);
	TextDrawFont(tdFactionSafe[3], 4);
	TextDrawSetProportional(tdFactionSafe[3], 0);

	tdFactionSafe[4] = TextDrawCreate(324.995910, 236.499938, "LD_SPAC:white");
	TextDrawTextSize(tdFactionSafe[4], 68.000000, 67.000000);
	TextDrawAlignment(tdFactionSafe[4], 1);
	TextDrawColor(tdFactionSafe[4], 170);
	TextDrawSetShadow(tdFactionSafe[4], 0);
	TextDrawBackgroundColor(tdFactionSafe[4], 255);
	TextDrawFont(tdFactionSafe[4], 4);
	TextDrawSetProportional(tdFactionSafe[4], 0);

	tdFactionSafe[5] = TextDrawCreate(402.495910, 236.499938, "LD_SPAC:white");
	TextDrawTextSize(tdFactionSafe[5], 68.000000, 67.000000);
	TextDrawAlignment(tdFactionSafe[5], 1);
	TextDrawColor(tdFactionSafe[5], 170);
	TextDrawSetShadow(tdFactionSafe[5], 0);
	TextDrawBackgroundColor(tdFactionSafe[5], 255);
	TextDrawFont(tdFactionSafe[5], 4);
	TextDrawSetProportional(tdFactionSafe[5], 0);

	tdFactionSafe[6] = TextDrawCreate(165.131515, 226.666595, "\\");
	TextDrawTextSize(tdFactionSafe[6], 78.000000, 72.000000);
	TextDrawAlignment(tdFactionSafe[6], 1);
	TextDrawColor(tdFactionSafe[6], -1);
	TextDrawBackgroundColor(tdFactionSafe[6], 0);
	TextDrawSetShadow(tdFactionSafe[6], 0);
	TextDrawFont(tdFactionSafe[6], 5);
	TextDrawSetProportional(tdFactionSafe[6], 0);
	TextDrawSetPreviewModel(tdFactionSafe[6], 1212);
	TextDrawSetPreviewRot(tdFactionSafe[6], -45.000000, 0.000000, 45.000000, 1.000000);

	tdFactionSafe[7] = TextDrawCreate(242.931655, 221.499969, "\\");
	TextDrawTextSize(tdFactionSafe[7], 76.000000, 88.000000);
	TextDrawAlignment(tdFactionSafe[7], 1);
	TextDrawColor(tdFactionSafe[7], -1);
	TextDrawBackgroundColor(tdFactionSafe[7], 0);
	TextDrawSetShadow(tdFactionSafe[7], 0);
	TextDrawFont(tdFactionSafe[7], 5);
	TextDrawSetProportional(tdFactionSafe[7], 0);
	TextDrawSetPreviewModel(tdFactionSafe[7], 2358);
	TextDrawSetPreviewRot(tdFactionSafe[7], -25.000000, 0.000000, -215.000000, 1.000000);

	tdFactionSafe[8] = TextDrawCreate(328.711334, 217.416595, "\\");
	TextDrawTextSize(tdFactionSafe[8], 67.000000, 92.000000);
	TextDrawAlignment(tdFactionSafe[8], 1);
	TextDrawColor(tdFactionSafe[8], -1);
	TextDrawBackgroundColor(tdFactionSafe[8], 0);
	TextDrawSetShadow(tdFactionSafe[8], 0);
	TextDrawFont(tdFactionSafe[8], 5);
	TextDrawSetProportional(tdFactionSafe[8], 0);
	TextDrawSetPreviewModel(tdFactionSafe[8], 1279);
	TextDrawSetPreviewRot(tdFactionSafe[8], 45.000000, 30.000000, 0.000000, 1.000000);

	tdFactionSafe[9] = TextDrawCreate(378.568542, 209.249938, "\\");
	TextDrawTextSize(tdFactionSafe[9], 116.000000, 120.000000);
	TextDrawAlignment(tdFactionSafe[9], 1);
	TextDrawColor(tdFactionSafe[9], -1191201537);
	TextDrawBackgroundColor(tdFactionSafe[9], 0);
	TextDrawSetShadow(tdFactionSafe[9], 0);
	TextDrawFont(tdFactionSafe[9], 5);
	TextDrawSetProportional(tdFactionSafe[9], 0);
	TextDrawSetPreviewModel(tdFactionSafe[9], 19473);
	TextDrawSetPreviewRot(tdFactionSafe[9], 0.000000, 0.000000, 180.000000, 1.000000);