
    tdRacing[0] = TextDrawCreate(588.000183, 292.159240, "/-");
    TextDrawLetterSize(tdRacing[0], 0.285666, 1.512889);
    TextDrawTextSize(tdRacing[0], 615.000000, 0.000000);
    TextDrawAlignment(tdRacing[0], 1);
    TextDrawColor(tdRacing[0], -1523963137);
    TextDrawSetShadow(tdRacing[0], 0);
    TextDrawSetOutline(tdRacing[0], 1);
    TextDrawBackgroundColor(tdRacing[0], 255);
    TextDrawFont(tdRacing[0], 2);
    TextDrawSetProportional(tdRacing[0], 1);

    tdRacing[1] = TextDrawCreate(578.333801, 313.200378, "00:00");
    TextDrawLetterSize(tdRacing[1], 0.240333, 1.357703);
    TextDrawTextSize(tdRacing[1], 668.000000, 0.000000);
    TextDrawAlignment(tdRacing[1], 1);
    TextDrawColor(tdRacing[1], -1);
    TextDrawSetShadow(tdRacing[1], 0);
    TextDrawSetOutline(tdRacing[1], 1);
    TextDrawBackgroundColor(tdRacing[1], 255);
    TextDrawFont(tdRacing[1], 2);
    TextDrawSetProportional(tdRacing[1], 1);

    tdRacing[2] = TextDrawCreate(565.600341, 313.144561, "ld_grav:timer");
    TextDrawTextSize(tdRacing[2], 11.000000, 12.000000);
    TextDrawAlignment(tdRacing[2], 1);
    TextDrawColor(tdRacing[2], -1);
    TextDrawSetShadow(tdRacing[2], 0);
    TextDrawBackgroundColor(tdRacing[2], 255);
    TextDrawFont(tdRacing[2], 4);
    TextDrawSetProportional(tdRacing[2], 0);

    tdRacing[3] = TextDrawCreate(318.333374, 372.103668, "~W~Pritisni ~Y~levi klik ~W~da aktiviras ~B~~H~nitro~N~~W~Pritisni ~Y~2 ~W~da ~G~~H~popravis ~W~vozilo~N~Pritisni ~Y~Y ~W~da ~G~~H~okrenes ~W~prevrnuto vozilo");
    TextDrawLetterSize(tdRacing[3], 0.137666, 0.832592);
    TextDrawTextSize(tdRacing[3], 0.000000, 241.000000);
    TextDrawAlignment(tdRacing[3], 2);
    TextDrawColor(tdRacing[3], -1);
    TextDrawSetShadow(tdRacing[3], 0);
    TextDrawSetOutline(tdRacing[3], 1);
    TextDrawBackgroundColor(tdRacing[3], 255);
    TextDrawFont(tdRacing[3], 2);
    TextDrawSetProportional(tdRacing[3], 1);