    tdMaterialsDelivery[WD_TIMER] = TextDrawCreate(494.800292, 178.987411, "VREME:      --:--");
    TextDrawLetterSize(tdMaterialsDelivery[WD_TIMER], 0.319332, 1.776666);
    TextDrawTextSize(tdMaterialsDelivery[WD_TIMER], 638.000000, 0.000000);
    TextDrawAlignment(tdMaterialsDelivery[WD_TIMER], 1);
    TextDrawColor(tdMaterialsDelivery[WD_TIMER], -1580072961);
    TextDrawSetShadow(tdMaterialsDelivery[WD_TIMER], 0);
    TextDrawSetOutline(tdMaterialsDelivery[WD_TIMER], 1);
    TextDrawBackgroundColor(tdMaterialsDelivery[WD_TIMER], 255);
    TextDrawFont(tdMaterialsDelivery[WD_TIMER], 2);
    TextDrawSetProportional(tdMaterialsDelivery[WD_TIMER], 1);

    tdMaterialsDelivery[WD_COUNTER] = TextDrawCreate(494.800201, 195.302703, "KUTIJE:      --/--");
    TextDrawLetterSize(tdMaterialsDelivery[WD_COUNTER], 0.319332, 1.776666);
    TextDrawTextSize(tdMaterialsDelivery[WD_COUNTER], 638.000000, 0.000000);
    TextDrawAlignment(tdMaterialsDelivery[WD_COUNTER], 1);
    TextDrawColor(tdMaterialsDelivery[WD_COUNTER], -387383297);
    TextDrawSetShadow(tdMaterialsDelivery[WD_COUNTER], 0);
    TextDrawSetOutline(tdMaterialsDelivery[WD_COUNTER], 1);
    TextDrawBackgroundColor(tdMaterialsDelivery[WD_COUNTER], 255);
    TextDrawFont(tdMaterialsDelivery[WD_COUNTER], 2);
    TextDrawSetProportional(tdMaterialsDelivery[WD_COUNTER], 1);

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////    

    tdBankRobTime = TextDrawCreate(494.800292, 178.987411, "VREME:      --:--");
    TextDrawLetterSize(tdBankRobTime, 0.319332, 1.776666);
    TextDrawTextSize(tdBankRobTime, 638.000000, 0.000000);
    TextDrawAlignment(tdBankRobTime, 1);
    TextDrawColor(tdBankRobTime, -1580072961);
    TextDrawSetShadow(tdBankRobTime, 0);
    TextDrawSetOutline(tdBankRobTime, 1);
    TextDrawBackgroundColor(tdBankRobTime, 255);
    TextDrawFont(tdBankRobTime, 2);
    TextDrawSetProportional(tdBankRobTime, 1);

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////    

    tdJewelryRobTime = TextDrawCreate(494.800292, 178.987411, "VREME:      --:--");
    TextDrawLetterSize(tdJewelryRobTime, 0.319332, 1.776666);
    TextDrawTextSize(tdJewelryRobTime, 638.000000, 0.000000);
    TextDrawAlignment(tdJewelryRobTime, 1);
    TextDrawColor(tdJewelryRobTime, -1580072961);
    TextDrawSetShadow(tdJewelryRobTime, 0);
    TextDrawSetOutline(tdJewelryRobTime, 1);
    TextDrawBackgroundColor(tdJewelryRobTime, 255);
    TextDrawFont(tdJewelryRobTime, 2);
    TextDrawSetProportional(tdJewelryRobTime, 1);

    tdJewelryRobCounter = TextDrawCreate(494.800201, 195.302703, "KUTIJE:      --/--");
    TextDrawLetterSize(tdJewelryRobCounter, 0.319332, 1.776666);
    TextDrawTextSize(tdJewelryRobCounter, 638.000000, 0.000000);
    TextDrawAlignment(tdJewelryRobCounter, 1);
    TextDrawColor(tdJewelryRobCounter, -387383297);
    TextDrawSetShadow(tdJewelryRobCounter, 0);
    TextDrawSetOutline(tdJewelryRobCounter, 1);
    TextDrawBackgroundColor(tdJewelryRobCounter, 255);
    TextDrawFont(tdJewelryRobCounter, 2);
    TextDrawSetProportional(tdJewelryRobCounter, 1);

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////    

    tdLMSEvent = TextDrawCreate(494.800292, 178.987411, "LMS:      --");
    TextDrawLetterSize(tdLMSEvent, 0.319332, 1.776666);
    TextDrawTextSize(tdLMSEvent, 638.000000, 0.000000);
    TextDrawAlignment(tdLMSEvent, 1);
    TextDrawColor(tdLMSEvent, -1580072961);
    TextDrawSetShadow(tdLMSEvent, 0);
    TextDrawSetOutline(tdLMSEvent, 1);
    TextDrawBackgroundColor(tdLMSEvent, 255);
    TextDrawFont(tdLMSEvent, 2);
    TextDrawSetProportional(tdLMSEvent, 1);