    // Kradja vozila
    tdSkill[SKILL_ROBBERY_CAR] = TextDrawCreate(264.534271, 348.792907, "");
    TextDrawTextSize(tdSkill[SKILL_ROBBERY_CAR], 54.000000, 57.000000);
    TextDrawAlignment(tdSkill[SKILL_ROBBERY_CAR], 1);
    TextDrawColor(tdSkill[SKILL_ROBBERY_CAR], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_ROBBERY_CAR], 0);
    TextDrawSetShadow(tdSkill[SKILL_ROBBERY_CAR], 0);
    TextDrawFont(tdSkill[SKILL_ROBBERY_CAR], 5);
    TextDrawSetProportional(tdSkill[SKILL_ROBBERY_CAR], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_ROBBERY_CAR], 411);
    TextDrawSetPreviewRot(tdSkill[SKILL_ROBBERY_CAR], -10.000000, 0.000000, -30.000000, 1.000000);
    TextDrawSetPreviewVehCol(tdSkill[SKILL_ROBBERY_CAR], 5, 1);

    // Hapsenje
    tdSkill[SKILL_ARREST] = TextDrawCreate(265.867645, 358.333587, ""); // Police line do not cross
    TextDrawTextSize(tdSkill[SKILL_ARREST], 100.000000, 63.000000);
    TextDrawAlignment(tdSkill[SKILL_ARREST], 1);
    TextDrawColor(tdSkill[SKILL_ARREST], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_ARREST], 0);
    TextDrawSetShadow(tdSkill[SKILL_ARREST], 0);
    TextDrawFont(tdSkill[SKILL_ARREST], 5);
    TextDrawSetProportional(tdSkill[SKILL_ARREST], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_ARREST], 19834);
    TextDrawSetPreviewRot(tdSkill[SKILL_ARREST], 0.000000, 0.000000, 0.000000, 0.500000);
    tdSkill[SKILL_ARREST2] = TextDrawCreate(278.000000, 359.503753, ""); // zvezdica
    TextDrawTextSize(tdSkill[SKILL_ARREST2], 23.000000, 26.000000);
    TextDrawAlignment(tdSkill[SKILL_ARREST2], 1);
    TextDrawColor(tdSkill[SKILL_ARREST2], -65281);
    TextDrawBackgroundColor(tdSkill[SKILL_ARREST2], 0);
    TextDrawSetShadow(tdSkill[SKILL_ARREST2], 0);
    TextDrawFont(tdSkill[SKILL_ARREST2], 5);
    TextDrawSetProportional(tdSkill[SKILL_ARREST2], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_ARREST2], 1247);
    TextDrawSetPreviewRot(tdSkill[SKILL_ARREST2], 0.000000, 0.000000, 0.000000, 1.000000);

    // AK-47
    tdSkill[SKILL_TURF_DEFENSE] = TextDrawCreate(252.534301, 356.259490, "");
    TextDrawTextSize(tdSkill[SKILL_TURF_DEFENSE], 54.000000, 56.000000);
    TextDrawAlignment(tdSkill[SKILL_TURF_DEFENSE], 1);
    TextDrawColor(tdSkill[SKILL_TURF_DEFENSE], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_TURF_DEFENSE], 0);
    TextDrawSetShadow(tdSkill[SKILL_TURF_DEFENSE], 0);
    TextDrawFont(tdSkill[SKILL_TURF_DEFENSE], 5);
    TextDrawSetProportional(tdSkill[SKILL_TURF_DEFENSE], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_TURF_DEFENSE], 355);
    TextDrawSetPreviewRot(tdSkill[SKILL_TURF_DEFENSE], -20.000000, 40.000000, 200.000000, 2.500000);

    // AK-47
    tdSkill[SKILL_TURF_DEFENSE_FAIL] = TextDrawCreate(252.534301, 356.259490, "");
    TextDrawTextSize(tdSkill[SKILL_TURF_DEFENSE_FAIL], 54.000000, 56.000000);
    TextDrawAlignment(tdSkill[SKILL_TURF_DEFENSE_FAIL], 1);
    TextDrawColor(tdSkill[SKILL_TURF_DEFENSE_FAIL], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_TURF_DEFENSE_FAIL], 0);
    TextDrawSetShadow(tdSkill[SKILL_TURF_DEFENSE_FAIL], 0);
    TextDrawFont(tdSkill[SKILL_TURF_DEFENSE_FAIL], 5);
    TextDrawSetProportional(tdSkill[SKILL_TURF_DEFENSE_FAIL], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_TURF_DEFENSE_FAIL], 355);
    TextDrawSetPreviewRot(tdSkill[SKILL_TURF_DEFENSE_FAIL], -20.000000, 40.000000, 200.000000, 2.500000);

    // AK-47
    tdSkill[SKILL_TURF_TAKEOVER] = TextDrawCreate(252.534301, 356.259490, "");
    TextDrawTextSize(tdSkill[SKILL_TURF_TAKEOVER], 54.000000, 56.000000);
    TextDrawAlignment(tdSkill[SKILL_TURF_TAKEOVER], 1);
    TextDrawColor(tdSkill[SKILL_TURF_TAKEOVER], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_TURF_TAKEOVER], 0);
    TextDrawSetShadow(tdSkill[SKILL_TURF_TAKEOVER], 0);
    TextDrawFont(tdSkill[SKILL_TURF_TAKEOVER], 5);
    TextDrawSetProportional(tdSkill[SKILL_TURF_TAKEOVER], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_TURF_TAKEOVER], 355);
    TextDrawSetPreviewRot(tdSkill[SKILL_TURF_TAKEOVER], -20.000000, 40.000000, 200.000000, 2.500000);

    // AK-47
    tdSkill[SKILL_TURF_TAKEOVER_FAIL] = TextDrawCreate(252.534301, 356.259490, "");
    TextDrawTextSize(tdSkill[SKILL_TURF_TAKEOVER_FAIL], 54.000000, 56.000000);
    TextDrawAlignment(tdSkill[SKILL_TURF_TAKEOVER_FAIL], 1);
    TextDrawColor(tdSkill[SKILL_TURF_TAKEOVER_FAIL], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_TURF_TAKEOVER_FAIL], 0);
    TextDrawSetShadow(tdSkill[SKILL_TURF_TAKEOVER_FAIL], 0);
    TextDrawFont(tdSkill[SKILL_TURF_TAKEOVER_FAIL], 5);
    TextDrawSetProportional(tdSkill[SKILL_TURF_TAKEOVER_FAIL], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_TURF_TAKEOVER_FAIL], 355);
    TextDrawSetPreviewRot(tdSkill[SKILL_TURF_TAKEOVER_FAIL], -20.000000, 40.000000, 200.000000, 2.500000);

    // AK-47
    tdSkill[SKILL_WAR_WIN] = TextDrawCreate(252.534301, 356.259490, "");
    TextDrawTextSize(tdSkill[SKILL_WAR_WIN], 54.000000, 56.000000);
    TextDrawAlignment(tdSkill[SKILL_WAR_WIN], 1);
    TextDrawColor(tdSkill[SKILL_WAR_WIN], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_WAR_WIN], 0);
    TextDrawSetShadow(tdSkill[SKILL_WAR_WIN], 0);
    TextDrawFont(tdSkill[SKILL_WAR_WIN], 5);
    TextDrawSetProportional(tdSkill[SKILL_WAR_WIN], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_WAR_WIN], 355);
    TextDrawSetPreviewRot(tdSkill[SKILL_WAR_WIN], -20.000000, 40.000000, 200.000000, 2.500000);

    // AK-47
    tdSkill[SKILL_WAR_LOSE] = TextDrawCreate(252.534301, 356.259490, "");
    TextDrawTextSize(tdSkill[SKILL_WAR_LOSE], 54.000000, 56.000000);
    TextDrawAlignment(tdSkill[SKILL_WAR_LOSE], 1);
    TextDrawColor(tdSkill[SKILL_WAR_LOSE], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_WAR_LOSE], 0);
    TextDrawSetShadow(tdSkill[SKILL_WAR_LOSE], 0);
    TextDrawFont(tdSkill[SKILL_WAR_LOSE], 5);
    TextDrawSetProportional(tdSkill[SKILL_WAR_LOSE], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_WAR_LOSE], 355);
    TextDrawSetPreviewRot(tdSkill[SKILL_WAR_LOSE], -20.000000, 40.000000, 200.000000, 2.500000);

    // Zlatara
    tdSkill[SKILL_ROBBERY_JEWELRY] = TextDrawCreate(253.534103, 346.203948, "");
    TextDrawTextSize(tdSkill[SKILL_ROBBERY_JEWELRY], 58.000000, 60.000000);
    TextDrawAlignment(tdSkill[SKILL_ROBBERY_JEWELRY], 1);
    TextDrawColor(tdSkill[SKILL_ROBBERY_JEWELRY], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_ROBBERY_JEWELRY], 0);
    TextDrawSetShadow(tdSkill[SKILL_ROBBERY_JEWELRY], 0);
    TextDrawFont(tdSkill[SKILL_ROBBERY_JEWELRY], 5);
    TextDrawSetProportional(tdSkill[SKILL_ROBBERY_JEWELRY], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_ROBBERY_JEWELRY], 19941);
    TextDrawSetPreviewRot(tdSkill[SKILL_ROBBERY_JEWELRY], -45.000000, 0.000000, 240.000000, 1.399999);

    // Market 24/7
    tdSkill[SKILL_ROBBERY_247] = TextDrawCreate(271.477050, 357.820678, "");
    TextDrawTextSize(tdSkill[SKILL_ROBBERY_247], 32.000000, 33.000000);
    TextDrawAlignment(tdSkill[SKILL_ROBBERY_247], 1);
    TextDrawColor(tdSkill[SKILL_ROBBERY_247], -1);
    TextDrawSetShadow(tdSkill[SKILL_ROBBERY_247], 0);
    TextDrawFont(tdSkill[SKILL_ROBBERY_247], 5);
    TextDrawSetProportional(tdSkill[SKILL_ROBBERY_247], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_ROBBERY_247], 1514);
    TextDrawSetPreviewRot(tdSkill[SKILL_ROBBERY_247], -10.000000, 0.000000, -30.000000, 0.699999);

    // Dzeparenje
    tdSkill[SKILL_PICKPOCKET] = TextDrawCreate(253.534103, 346.203948, "");
    TextDrawTextSize(tdSkill[SKILL_PICKPOCKET], 58.000000, 60.000000);
    TextDrawAlignment(tdSkill[SKILL_PICKPOCKET], 1);
    TextDrawColor(tdSkill[SKILL_PICKPOCKET], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_PICKPOCKET], 0);
    TextDrawSetShadow(tdSkill[SKILL_PICKPOCKET], 0);
    TextDrawFont(tdSkill[SKILL_PICKPOCKET], 5);
    TextDrawSetProportional(tdSkill[SKILL_PICKPOCKET], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_PICKPOCKET], 1212);
    TextDrawSetPreviewRot(tdSkill[SKILL_PICKPOCKET], -30.000000, 0.000000, 250.000000, 1.399999);

    // Banka
    tdSkill[SKILL_ROBBERY_BANK] = TextDrawCreate(250.567291, 347.733612, "");
    TextDrawTextSize(tdSkill[SKILL_ROBBERY_BANK], 58.000000, 60.000000);
    TextDrawAlignment(tdSkill[SKILL_ROBBERY_BANK], 1);
    TextDrawColor(tdSkill[SKILL_ROBBERY_BANK], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_ROBBERY_BANK], 0);
    TextDrawSetShadow(tdSkill[SKILL_ROBBERY_BANK], 0);
    TextDrawFont(tdSkill[SKILL_ROBBERY_BANK], 5);
    TextDrawSetProportional(tdSkill[SKILL_ROBBERY_BANK], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_ROBBERY_BANK], 1550);
    TextDrawSetPreviewRot(tdSkill[SKILL_ROBBERY_BANK], -25.000000, 0.000000, 240.000000, 1.399999);

    // Bankomat
    tdSkill[SKILL_ROBBERY_ATM] = TextDrawCreate(250.567291, 347.733612, "");
    TextDrawTextSize(tdSkill[SKILL_ROBBERY_ATM], 58.000000, 60.000000);
    TextDrawAlignment(tdSkill[SKILL_ROBBERY_ATM], 1);
    TextDrawColor(tdSkill[SKILL_ROBBERY_ATM], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_ROBBERY_ATM], 0);
    TextDrawSetShadow(tdSkill[SKILL_ROBBERY_ATM], 0);
    TextDrawFont(tdSkill[SKILL_ROBBERY_ATM], 5);
    TextDrawSetProportional(tdSkill[SKILL_ROBBERY_ATM], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_ROBBERY_ATM], 2942);
    TextDrawSetPreviewRot(tdSkill[SKILL_ROBBERY_ATM], 180.000000, 180.000000, 0.000000, 1.399999);

    // LTA
    tdSkill[SKILL_LTA] = TextDrawCreate(272.867645, 361.237426, "");
    TextDrawTextSize(tdSkill[SKILL_LTA], 32.000000, 33.000000);
    TextDrawAlignment(tdSkill[SKILL_LTA], 1);
    TextDrawColor(tdSkill[SKILL_LTA], -1);
    TextDrawBackgroundColor(tdSkill[SKILL_LTA], 0);
    TextDrawSetShadow(tdSkill[SKILL_LTA], 0);
    TextDrawFont(tdSkill[SKILL_LTA], 5);
    TextDrawSetProportional(tdSkill[SKILL_LTA], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_LTA], 1314);
    TextDrawSetPreviewRot(tdSkill[SKILL_LTA], -10.000000, 0.000000, -30.000000, 1.000000);

    // Delivery / Dostava materijala i municije
    tdSkill[SKILL_DELIVERY] = TextDrawCreate(261.776458, 339.919586, "");
    TextDrawTextSize(tdSkill[SKILL_DELIVERY], 51.669887, 72.030006);
    TextDrawAlignment(tdSkill[SKILL_DELIVERY], 1);
    TextDrawColor(tdSkill[SKILL_DELIVERY], -1);
    TextDrawSetShadow(tdSkill[SKILL_DELIVERY], 0);
    TextDrawFont(tdSkill[SKILL_DELIVERY], 5);
    TextDrawSetProportional(tdSkill[SKILL_DELIVERY], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_DELIVERY], 482);
    TextDrawSetPreviewRot(tdSkill[SKILL_DELIVERY], -10.000000, 0.000000, -30.000000, 1.000000);
    TextDrawSetPreviewVehCol(tdSkill[SKILL_DELIVERY], 5, 1);

    // Skladiste sa vagonima (oruzjem) weapons_drop.pwn
    tdSkill[SKILL_WEAPONS_DROP] = TextDrawCreate(263.036773, 352.336883, "");
    TextDrawTextSize(tdSkill[SKILL_WEAPONS_DROP], 40.000000, 49.000000);
    TextDrawAlignment(tdSkill[SKILL_WEAPONS_DROP], 1);
    TextDrawColor(tdSkill[SKILL_WEAPONS_DROP], -1);
    TextDrawSetShadow(tdSkill[SKILL_WEAPONS_DROP], 0);
    TextDrawFont(tdSkill[SKILL_WEAPONS_DROP], 5);
    TextDrawSetProportional(tdSkill[SKILL_WEAPONS_DROP], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_WEAPONS_DROP], 3014);
    TextDrawSetPreviewRot(tdSkill[SKILL_WEAPONS_DROP], -30.000000, 0.000000, 45.000000, 1.200000);

    tdSkill[SKILL_SUSPECT_KILL] = TextDrawCreate(263.036773, 352.336883, "");
    TextDrawTextSize(tdSkill[SKILL_SUSPECT_KILL], 40.000000, 49.000000);
    TextDrawAlignment(tdSkill[SKILL_SUSPECT_KILL], 1);
    TextDrawColor(tdSkill[SKILL_SUSPECT_KILL], -1);
    TextDrawSetShadow(tdSkill[SKILL_SUSPECT_KILL], 0);
    TextDrawFont(tdSkill[SKILL_SUSPECT_KILL], 5);
    TextDrawSetProportional(tdSkill[SKILL_SUSPECT_KILL], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_SUSPECT_KILL], 1254);
    TextDrawSetPreviewRot(tdSkill[SKILL_SUSPECT_KILL], -15.000000, 0.000000, 38.000000, 1.200000);

    tdSkill[SKILL_BANKWIN] = TextDrawCreate(263.036773, 352.336883, "");
    TextDrawTextSize(tdSkill[SKILL_BANKWIN], 40.000000, 49.000000);
    TextDrawAlignment(tdSkill[SKILL_BANKWIN], 1);
    TextDrawColor(tdSkill[SKILL_BANKWIN], -1);
    TextDrawSetShadow(tdSkill[SKILL_BANKWIN], 0);
    TextDrawFont(tdSkill[SKILL_BANKWIN], 5);
    TextDrawSetProportional(tdSkill[SKILL_BANKWIN], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_BANKWIN], 1254);
    TextDrawSetPreviewRot(tdSkill[SKILL_BANKWIN], -15.000000, 0.000000, 38.000000, 1.200000); // SKILL_BANKWIN

    tdSkill[SKILL_JEWWIN] = TextDrawCreate(263.036773, 352.336883, "");
    TextDrawTextSize(tdSkill[SKILL_JEWWIN], 40.000000, 49.000000);
    TextDrawAlignment(tdSkill[SKILL_JEWWIN], 1);
    TextDrawColor(tdSkill[SKILL_JEWWIN], -1);
    TextDrawSetShadow(tdSkill[SKILL_JEWWIN], 0);
    TextDrawFont(tdSkill[SKILL_JEWWIN], 5);
    TextDrawSetProportional(tdSkill[SKILL_JEWWIN], 0);
    TextDrawSetPreviewModel(tdSkill[SKILL_JEWWIN], 1254);
    TextDrawSetPreviewRot(tdSkill[SKILL_JEWWIN], -15.000000, 0.000000, 38.000000, 1.200000); // SKILL_BANKWIN