    
    tdSpec[0] = TextDrawCreate(497.855438, 132.249954, "LD_SPAC:white");
    TextDrawTextSize(tdSpec[0], 104.000000, 100.000000);
    TextDrawAlignment(tdSpec[0], 1);
    TextDrawColor(tdSpec[0], 128);
    TextDrawSetShadow(tdSpec[0], 0);
    TextDrawBackgroundColor(tdSpec[0], 255);
    TextDrawFont(tdSpec[0], 4);
    TextDrawSetProportional(tdSpec[0], 0);

    tdSpec[1] = TextDrawCreate(540.190246, 152.666687, "Nivo:~N~Novac:~N~Banka:~N~Grupa:~N~Wanted:~N~Health:~N~Armour:~N~ENT / VW:~N~");
    TextDrawLetterSize(tdSpec[1], 0.166676, 0.987499);
    TextDrawAlignment(tdSpec[1], 3);
    TextDrawColor(tdSpec[1], -2139062017);
    TextDrawSetShadow(tdSpec[1], 0);
    TextDrawSetOutline(tdSpec[1], 1);
    TextDrawBackgroundColor(tdSpec[1], 255);
    TextDrawFont(tdSpec[1], 2);
    TextDrawSetProportional(tdSpec[1], 1);