    tdWantedLevel[0] = TextDrawCreate(292.261993, 407.849426, "LD_BEAT:CHIT");
    TextDrawTextSize(tdWantedLevel[0], -20.000000, 16.000000);
    TextDrawAlignment(tdWantedLevel[0], 1);
    TextDrawColor(tdWantedLevel[0], 255);
    TextDrawSetShadow(tdWantedLevel[0], 0);
    TextDrawBackgroundColor(tdWantedLevel[0], 255);
    TextDrawFont(tdWantedLevel[0], 4);
    TextDrawSetProportional(tdWantedLevel[0], 0);

    tdWantedLevel[1] = TextDrawCreate(360.817749, 407.849426, "LD_BEAT:CHIT");
    TextDrawTextSize(tdWantedLevel[1], -20.000000, 16.000000);
    TextDrawAlignment(tdWantedLevel[1], 1);
    TextDrawColor(tdWantedLevel[1], 255);
    TextDrawSetShadow(tdWantedLevel[1], 0);
    TextDrawBackgroundColor(tdWantedLevel[1], 255);
    TextDrawFont(tdWantedLevel[1], 4);
    TextDrawSetProportional(tdWantedLevel[1], 0);

    // tdWantedLevel[2] = TextDrawCreate(316.793273, 412.616271, "box");
    // TextDrawLetterSize(tdWantedLevel[2], 0.000000, 0.650429);
    // TextDrawTextSize(tdWantedLevel[2], 0.000000, 65.000000);
    // TextDrawAlignment(tdWantedLevel[2], 2);
    // TextDrawColor(tdWantedLevel[2], -1);
    // TextDrawUseBox(tdWantedLevel[2], 1);
    // TextDrawBoxColor(tdWantedLevel[2], 255);
    // TextDrawSetShadow(tdWantedLevel[2], 0);
    // TextDrawBackgroundColor(tdWantedLevel[2], 255);
    // TextDrawFont(tdWantedLevel[2], 1);
    // TextDrawSetProportional(tdWantedLevel[2], 1);

    tdWantedLevel[2] = TextDrawCreate(282.366790, 409.896270, "LD_SPAC:white");
    TextDrawTextSize(tdWantedLevel[2], 69.000000, 11.149979);
    TextDrawAlignment(tdWantedLevel[2], 1);
    TextDrawColor(tdWantedLevel[2], 255);
    TextDrawSetShadow(tdWantedLevel[2], 0);
    TextDrawBackgroundColor(tdWantedLevel[2], 255);
    TextDrawFont(tdWantedLevel[2], 4);
    TextDrawSetProportional(tdWantedLevel[2], 0);

    tdWantedLevel[3] = TextDrawCreate(281.276397, 419.334014, "particle:lamp_shad_64");
    TextDrawTextSize(tdWantedLevel[3], 73.000000, -9.000000);
    TextDrawAlignment(tdWantedLevel[3], 1);
    TextDrawColor(tdWantedLevel[3], -16777186);
    TextDrawSetShadow(tdWantedLevel[3], 0);
    TextDrawBackgroundColor(tdWantedLevel[3], 255);
    TextDrawFont(tdWantedLevel[3], 4);
    TextDrawSetProportional(tdWantedLevel[3], 0);