    tdWar[0] = TextDrawCreate(77.300003, 176.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[0], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[0], 3);
    TextDrawColor(tdWar[0], -1);
    TextDrawUseBox(tdWar[0], true);
    TextDrawBoxColor(tdWar[0], 6618980);
    TextDrawSetShadow(tdWar[0], 0);
    TextDrawSetOutline(tdWar[0], 1);
    TextDrawBackgroundColor(tdWar[0], 51);
    TextDrawFont(tdWar[0], 1);
    TextDrawSetProportional(tdWar[0], 1);

    tdWar[1] = TextDrawCreate(77.300003, 190.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[1], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[1], 3);
    TextDrawColor(tdWar[1], -1);
    TextDrawUseBox(tdWar[1], true);
    TextDrawBoxColor(tdWar[1], 6618980);
    TextDrawSetShadow(tdWar[1], 0);
    TextDrawSetOutline(tdWar[1], 1);
    TextDrawBackgroundColor(tdWar[1], 51);
    TextDrawFont(tdWar[1], 1);
    TextDrawSetProportional(tdWar[1], 1);

    tdWar[2] = TextDrawCreate(77.300003, 204.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[2], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[2], 3);
    TextDrawColor(tdWar[2], -1);
    TextDrawUseBox(tdWar[2], true);
    TextDrawBoxColor(tdWar[2], 6618980);
    TextDrawSetShadow(tdWar[2], 0);
    TextDrawSetOutline(tdWar[2], 1);
    TextDrawBackgroundColor(tdWar[2], 51);
    TextDrawFont(tdWar[2], 1);
    TextDrawSetProportional(tdWar[2], 1);

    tdWar[3] = TextDrawCreate(77.300003, 218.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[3], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[3], 3);
    TextDrawColor(tdWar[3], -1);
    TextDrawUseBox(tdWar[3], true);
    TextDrawBoxColor(tdWar[3], 6618980);
    TextDrawSetShadow(tdWar[3], 0);
    TextDrawSetOutline(tdWar[3], 1);
    TextDrawBackgroundColor(tdWar[3], 51);
    TextDrawFont(tdWar[3], 1);
    TextDrawSetProportional(tdWar[3], 1);

    tdWar[4] = TextDrawCreate(77.300003, 232.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[4], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[4], 3);
    TextDrawColor(tdWar[4], -1);
    TextDrawUseBox(tdWar[4], true);
    TextDrawBoxColor(tdWar[4], 6618980);
    TextDrawSetShadow(tdWar[4], 0);
    TextDrawSetOutline(tdWar[4], 1);
    TextDrawBackgroundColor(tdWar[4], 51);
    TextDrawFont(tdWar[4], 1);
    TextDrawSetProportional(tdWar[4], 1);

    tdWar[5] = TextDrawCreate(77.300003, 246.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[5], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[5], 3);
    TextDrawColor(tdWar[5], -1);
    TextDrawUseBox(tdWar[5], true);
    TextDrawBoxColor(tdWar[5], 6618980);
    TextDrawSetShadow(tdWar[5], 0);
    TextDrawSetOutline(tdWar[5], 1);
    TextDrawBackgroundColor(tdWar[5], 51);
    TextDrawFont(tdWar[5], 1);
    TextDrawSetProportional(tdWar[5], 1);

    tdWar[6] = TextDrawCreate(77.300003, 260.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[6], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[6], 3);
    TextDrawColor(tdWar[6], -1);
    TextDrawUseBox(tdWar[6], true);
    TextDrawBoxColor(tdWar[6], 6618980);
    TextDrawSetShadow(tdWar[6], 0);
    TextDrawSetOutline(tdWar[6], 1);
    TextDrawBackgroundColor(tdWar[6], 51);
    TextDrawFont(tdWar[6], 1);
    TextDrawSetProportional(tdWar[6], 1);

    tdWar[7] = TextDrawCreate(77.300003, 274.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[7], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[7], 3);
    TextDrawColor(tdWar[7], -1);
    TextDrawUseBox(tdWar[7], true);
    TextDrawBoxColor(tdWar[7], 6618980);
    TextDrawSetShadow(tdWar[7], 0);
    TextDrawSetOutline(tdWar[7], 1);
    TextDrawBackgroundColor(tdWar[7], 51);
    TextDrawFont(tdWar[7], 1);
    TextDrawSetProportional(tdWar[7], 1);

    tdWar[8] = TextDrawCreate(77.300003, 288.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[8], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[8], 3);
    TextDrawColor(tdWar[8], -1);
    TextDrawUseBox(tdWar[8], true);
    TextDrawBoxColor(tdWar[8], 6618980);
    TextDrawSetShadow(tdWar[8], 0);
    TextDrawSetOutline(tdWar[8], 1);
    TextDrawBackgroundColor(tdWar[8], 51);
    TextDrawFont(tdWar[8], 1);
    TextDrawSetProportional(tdWar[8], 1);

    tdWar[9] = TextDrawCreate(77.300003, 302.000000, "Ucitavanje..."); // Tim 1 igrac
    TextDrawLetterSize(tdWar[9], 0.172000, 0.919700);
    TextDrawAlignment(tdWar[9], 3);
    TextDrawColor(tdWar[9], -1);
    TextDrawUseBox(tdWar[9], true);
    TextDrawBoxColor(tdWar[9], 6618980);
    TextDrawSetShadow(tdWar[9], 0);
    TextDrawSetOutline(tdWar[9], 1);
    TextDrawBackgroundColor(tdWar[9], 51);
    TextDrawFont(tdWar[9], 1);
    TextDrawSetProportional(tdWar[9], 1);

    tdWar[10] = TextDrawCreate(562.666870, 176.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[10], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[10], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[10], 1);
    TextDrawColor(tdWar[10], -1);
    TextDrawUseBox(tdWar[10], true);
    TextDrawBoxColor(tdWar[10], -16777116);
    TextDrawSetShadow(tdWar[10], 0);
    TextDrawSetOutline(tdWar[10], 1);
    TextDrawBackgroundColor(tdWar[10], 51);
    TextDrawFont(tdWar[10], 1);
    TextDrawSetProportional(tdWar[10], 1);

    tdWar[11] = TextDrawCreate(562.666870, 190.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[11], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[11], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[11], 1);
    TextDrawColor(tdWar[11], -1);
    TextDrawUseBox(tdWar[11], true);
    TextDrawBoxColor(tdWar[11], -16777116);
    TextDrawSetShadow(tdWar[11], 0);
    TextDrawSetOutline(tdWar[11], 1);
    TextDrawBackgroundColor(tdWar[11], 51);
    TextDrawFont(tdWar[11], 1);
    TextDrawSetProportional(tdWar[11], 1);

    tdWar[12] = TextDrawCreate(562.666870, 204.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[12], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[12], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[12], 1);
    TextDrawColor(tdWar[12], -1);
    TextDrawUseBox(tdWar[12], true);
    TextDrawBoxColor(tdWar[12], -16777116);
    TextDrawSetShadow(tdWar[12], 0);
    TextDrawSetOutline(tdWar[12], 1);
    TextDrawBackgroundColor(tdWar[12], 51);
    TextDrawFont(tdWar[12], 1);
    TextDrawSetProportional(tdWar[12], 1);

    tdWar[13] = TextDrawCreate(562.666870, 218.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[13], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[13], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[13], 1);
    TextDrawColor(tdWar[13], -1);
    TextDrawUseBox(tdWar[13], true);
    TextDrawBoxColor(tdWar[13], -16777116);
    TextDrawSetShadow(tdWar[13], 0);
    TextDrawSetOutline(tdWar[13], 1);
    TextDrawBackgroundColor(tdWar[13], 51);
    TextDrawFont(tdWar[13], 1);
    TextDrawSetProportional(tdWar[13], 1);

    tdWar[14] = TextDrawCreate(562.666870, 232.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[14], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[14], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[14], 1);
    TextDrawColor(tdWar[14], -1);
    TextDrawUseBox(tdWar[14], true);
    TextDrawBoxColor(tdWar[14], -16777116);
    TextDrawSetShadow(tdWar[14], 0);
    TextDrawSetOutline(tdWar[14], 1);
    TextDrawBackgroundColor(tdWar[14], 51);
    TextDrawFont(tdWar[14], 1);
    TextDrawSetProportional(tdWar[14], 1);

    tdWar[15] = TextDrawCreate(562.666870, 246.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[15], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[15], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[15], 1);
    TextDrawColor(tdWar[15], -1);
    TextDrawUseBox(tdWar[15], true);
    TextDrawBoxColor(tdWar[15], -16777116);
    TextDrawSetShadow(tdWar[15], 0);
    TextDrawSetOutline(tdWar[15], 1);
    TextDrawBackgroundColor(tdWar[15], 51);
    TextDrawFont(tdWar[15], 1);
    TextDrawSetProportional(tdWar[15], 1);

    tdWar[16] = TextDrawCreate(562.666870, 260.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[16], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[16], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[16], 1);
    TextDrawColor(tdWar[16], -1);
    TextDrawUseBox(tdWar[16], true);
    TextDrawBoxColor(tdWar[16], -16777116);
    TextDrawSetShadow(tdWar[16], 0);
    TextDrawSetOutline(tdWar[16], 1);
    TextDrawBackgroundColor(tdWar[16], 51);
    TextDrawFont(tdWar[16], 1);
    TextDrawSetProportional(tdWar[16], 1);

    tdWar[17] = TextDrawCreate(562.666870, 274.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[17], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[17], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[17], 1);
    TextDrawColor(tdWar[17], -1);
    TextDrawUseBox(tdWar[17], true);
    TextDrawBoxColor(tdWar[17], -16777116);
    TextDrawSetShadow(tdWar[17], 0);
    TextDrawSetOutline(tdWar[17], 1);
    TextDrawBackgroundColor(tdWar[17], 51);
    TextDrawFont(tdWar[17], 1);
    TextDrawSetProportional(tdWar[17], 1);

    tdWar[18] = TextDrawCreate(562.666870, 288.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[18], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[18], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[18], 1);
    TextDrawColor(tdWar[18], -1);
    TextDrawUseBox(tdWar[18], true);
    TextDrawBoxColor(tdWar[18], -16777116);
    TextDrawSetShadow(tdWar[18], 0);
    TextDrawSetOutline(tdWar[18], 1);
    TextDrawBackgroundColor(tdWar[18], 51);
    TextDrawFont(tdWar[18], 1);
    TextDrawSetProportional(tdWar[18], 1);

    tdWar[19] = TextDrawCreate(562.666870, 302.000000, "Ucitavanje..."); // Tim 2 igrac
    TextDrawLetterSize(tdWar[19], 0.172000, 0.919700);
    TextDrawTextSize(tdWar[19], 676.333374, -9.955554);
    TextDrawAlignment(tdWar[19], 1);
    TextDrawColor(tdWar[19], -1);
    TextDrawUseBox(tdWar[19], true);
    TextDrawBoxColor(tdWar[19], -16777116);
    TextDrawSetShadow(tdWar[19], 0);
    TextDrawSetOutline(tdWar[19], 1);
    TextDrawBackgroundColor(tdWar[19], 51);
    TextDrawFont(tdWar[19], 1);
    TextDrawSetProportional(tdWar[19], 1);

    tdWar[20] = TextDrawCreate(643.666625, 431.663085, "Box dole");
    TextDrawLetterSize(tdWar[20], 0.000000, 2.858232);
    TextDrawTextSize(tdWar[20], -2.333332, 0.000000);
    TextDrawAlignment(tdWar[20], 1);
    TextDrawColor(tdWar[20], 0);
    TextDrawUseBox(tdWar[20], true);
    TextDrawBoxColor(tdWar[20], 102);
    TextDrawSetShadow(tdWar[20], 0);
    TextDrawSetOutline(tdWar[20], 0);
    TextDrawFont(tdWar[20], 0);

    tdWar[21] = TextDrawCreate(2.333348, 432.651824, "WTM: ~w~122");
    TextDrawLetterSize(tdWar[21], 0.296999, 1.434074);
    TextDrawAlignment(tdWar[21], 1);
    TextDrawColor(tdWar[21], 6619135);
    TextDrawSetShadow(tdWar[21], 0);
    TextDrawSetOutline(tdWar[21], 1);
    TextDrawBackgroundColor(tdWar[21], 51);
    TextDrawFont(tdWar[21], 3);
    TextDrawSetProportional(tdWar[21], 1);

    tdWar[22] = TextDrawCreate(634.333496, 432.651824, "GSF: ~w~122");
    TextDrawLetterSize(tdWar[22], 0.296999, 1.434074);
    TextDrawAlignment(tdWar[22], 3);
    TextDrawColor(tdWar[22], -16776961);
    TextDrawSetShadow(tdWar[22], 0);
    TextDrawSetOutline(tdWar[22], 1);
    TextDrawBackgroundColor(tdWar[22], 51);
    TextDrawFont(tdWar[22], 3);
    TextDrawSetProportional(tdWar[22], 1);

    tdWar[23] = TextDrawCreate(316.999816, 432.237121, "13:01");
    TextDrawLetterSize(tdWar[23], 0.253666, 1.409185);
    TextDrawAlignment(tdWar[23], 2);
    TextDrawColor(tdWar[23], -65281);
    TextDrawSetShadow(tdWar[23], 0);
    TextDrawSetOutline(tdWar[23], 1);
    TextDrawBackgroundColor(tdWar[23], 51);
    TextDrawFont(tdWar[23], 2);
    TextDrawSetProportional(tdWar[23], 1);

    tdWar[24] = TextDrawCreate(189.666671, 432.237121, "Urban");
    TextDrawLetterSize(tdWar[24], 0.189665, 1.330368);
    TextDrawAlignment(tdWar[24], 2);
    TextDrawColor(tdWar[24], -1);
    TextDrawSetShadow(tdWar[24], 0);
    TextDrawSetOutline(tdWar[24], 1);
    TextDrawBackgroundColor(tdWar[24], 51);
    TextDrawFont(tdWar[24], 2);
    TextDrawSetProportional(tdWar[24], 1);

    tdWar[25] = TextDrawCreate(444.332946, 432.237121, "10  vs  10");
    TextDrawLetterSize(tdWar[25], 0.189665, 1.330368);
    TextDrawAlignment(tdWar[25], 2);
    TextDrawColor(tdWar[25], -1);
    TextDrawSetShadow(tdWar[25], 0);
    TextDrawSetOutline(tdWar[25], 1);
    TextDrawBackgroundColor(tdWar[25], 51);
    TextDrawFont(tdWar[25], 2);
    TextDrawSetProportional(tdWar[25], 1);