    tdWarResult[0] = TextDrawCreate(518.666748, 410.507415, "usebox");
    TextDrawLetterSize(tdWarResult[0], 0.000000, -26.688268);
    TextDrawTextSize(tdWarResult[0], 124.000000, 0.000000);
    TextDrawAlignment(tdWarResult[0], 1);
    TextDrawColor(tdWarResult[0], 0);
    TextDrawUseBox(tdWarResult[0], true);
    TextDrawBoxColor(tdWarResult[0], 225);
    TextDrawSetShadow(tdWarResult[0], 0);
    TextDrawSetOutline(tdWarResult[0], 0);
    TextDrawBackgroundColor(tdWarResult[0], -5963521);
    TextDrawFont(tdWarResult[0], 0);

    tdWarResult[1] = TextDrawCreate(515.333312, 174.477783, "usebox");
    TextDrawLetterSize(tdWarResult[1], 0.000000, 4.568929);
    TextDrawTextSize(tdWarResult[1], 123.666664, 0.000000);
    TextDrawAlignment(tdWarResult[1], 1);
    TextDrawColor(tdWarResult[1], 0);
    TextDrawUseBox(tdWarResult[1], true);
    TextDrawBoxColor(tdWarResult[1], 102);
    TextDrawSetShadow(tdWarResult[1], 0);
    TextDrawSetOutline(tdWarResult[1], 0);
    TextDrawFont(tdWarResult[1], 0);

    // Tim 1 skor
    tdWarResult[2] = TextDrawCreate(130.666671, 175.051849, "WTM   ~w~122"); 
    TextDrawLetterSize(tdWarResult[2], 0.343665, 1.707851);
    TextDrawAlignment(tdWarResult[2], 1);
    TextDrawColor(tdWarResult[2], 6605055);
    TextDrawSetShadow(tdWarResult[2], 0);
    TextDrawSetOutline(tdWarResult[2], 1);
    TextDrawBackgroundColor(tdWarResult[2], 51);
    TextDrawFont(tdWarResult[2], 3);
    TextDrawSetProportional(tdWarResult[2], 1);

    // Tim 2 skor
    tdWarResult[3] = TextDrawCreate(507.000000, 175.051849, "GSF  ~w~152");
    TextDrawLetterSize(tdWarResult[3], 0.355333, 1.807407);
    TextDrawAlignment(tdWarResult[3], 3);
    TextDrawColor(tdWarResult[3], -16776961);
    TextDrawSetShadow(tdWarResult[3], 0);
    TextDrawSetOutline(tdWarResult[3], 1);
    TextDrawBackgroundColor(tdWarResult[3], 51);
    TextDrawFont(tdWarResult[3], 3);
    TextDrawSetProportional(tdWarResult[3], 1);

    tdWarResult[4] = TextDrawCreate(130.000000, 201.599960, "Igrac               K     D     DMG                                Igrac               K     D     DMG");
    TextDrawLetterSize(tdWarResult[4], 0.220329, 0.998516);
    TextDrawAlignment(tdWarResult[4], 1);
    TextDrawColor(tdWarResult[4], -1);
    TextDrawSetShadow(tdWarResult[4], 0);
    TextDrawSetOutline(tdWarResult[4], 1);
    TextDrawBackgroundColor(tdWarResult[4], 51);
    TextDrawFont(tdWarResult[4], 1);
    TextDrawSetProportional(tdWarResult[4], 1);

    // Tim 1 spisak igraca
    tdWarResult[5] = TextDrawCreate(129.666671, 220.266647, "Frankie_Marcello~n~Craig_Collins~n~Mike_Murda~n~Frankie_Marcello~n~Craig_Collins~n~Mike_Murda~n~Frankie_Marcello~n~Craig_Collin");
    TextDrawLetterSize(tdWarResult[5], 0.156332, 0.857478);
    TextDrawAlignment(tdWarResult[5], 1);
    TextDrawColor(tdWarResult[5], -1);
    TextDrawSetShadow(tdWarResult[5], 0);
    TextDrawSetOutline(tdWarResult[5], 0);
    TextDrawBackgroundColor(tdWarResult[5], 51);
    TextDrawFont(tdWarResult[5], 1);
    TextDrawSetProportional(tdWarResult[5], 1);

    // Tim 1 ubistva
    tdWarResult[6] = TextDrawCreate(201.333358, 220.266647, "1~n~1~n~1~n~1~n~1~n~1~n~1~n~1~n~1~n~1");
    TextDrawLetterSize(tdWarResult[6], 0.156332, 0.857478);
    TextDrawAlignment(tdWarResult[6], 1);
    TextDrawColor(tdWarResult[6], -1);
    TextDrawSetShadow(tdWarResult[6], 0);
    TextDrawSetOutline(tdWarResult[6], 1);
    TextDrawBackgroundColor(tdWarResult[6], 51);
    TextDrawFont(tdWarResult[6], 1);
    TextDrawSetProportional(tdWarResult[6], 1);

    // Tim 1 smrti
    tdWarResult[7] = TextDrawCreate(223.666671, 220.266647, "2~n~2~n~2~n~2~n~2~n~2~n~2~n~2~n~2~n~2");
    TextDrawLetterSize(tdWarResult[7], 0.156332, 0.857478);
    TextDrawAlignment(tdWarResult[7], 1);
    TextDrawColor(tdWarResult[7], -1);
    TextDrawSetShadow(tdWarResult[7], 0);
    TextDrawSetOutline(tdWarResult[7], 1);
    TextDrawBackgroundColor(tdWarResult[7], 51);
    TextDrawFont(tdWarResult[7], 1);
    TextDrawSetProportional(tdWarResult[7], 1);

    // Tim 1 damage
    tdWarResult[8] = TextDrawCreate(245.999984, 220.266647, "3~n~3~n~3~n~3~n~3~n~3~n~3~n~3~n~3~n~3");
    TextDrawLetterSize(tdWarResult[8], 0.156332, 0.857478);
    TextDrawAlignment(tdWarResult[8], 1);
    TextDrawColor(tdWarResult[8], -1);
    TextDrawSetShadow(tdWarResult[8], 0);
    TextDrawSetOutline(tdWarResult[8], 1);
    TextDrawBackgroundColor(tdWarResult[8], 51);
    TextDrawFont(tdWarResult[8], 1);
    TextDrawSetProportional(tdWarResult[8], 1);

    // Tim 2 spisak igraca
    tdWarResult[9] = TextDrawCreate(375.666656, 220.266647, "Frankie_Marcello~n~Craig_Collins~n~Mike_Murda~n~Frankie_Marcello~n~Craig_Collins~n~Mike_Murda~n~Frankie_Marcello~n~Craig_Collin");
    TextDrawLetterSize(tdWarResult[9], 0.156332, 0.857478);
    TextDrawAlignment(tdWarResult[9], 1);
    TextDrawColor(tdWarResult[9], -1);
    TextDrawSetShadow(tdWarResult[9], 0);
    TextDrawSetOutline(tdWarResult[9], 0);
    TextDrawBackgroundColor(tdWarResult[9], 51);
    TextDrawFont(tdWarResult[9], 1);
    TextDrawSetProportional(tdWarResult[9], 1);

    // Tim 2 ubistva
    tdWarResult[10] = TextDrawCreate(447.333343, 220.266647, "1~n~1~n~1~n~1~n~1~n~1~n~1~n~1~n~1~n~1");
    TextDrawLetterSize(tdWarResult[10], 0.156332, 0.857478);
    TextDrawAlignment(tdWarResult[10], 1);
    TextDrawColor(tdWarResult[10], -1);
    TextDrawSetShadow(tdWarResult[10], 0);
    TextDrawSetOutline(tdWarResult[10], 1);
    TextDrawBackgroundColor(tdWarResult[10], 51);
    TextDrawFont(tdWarResult[10], 1);
    TextDrawSetProportional(tdWarResult[10], 1);

    // Tim 2 smrti
    tdWarResult[11] = TextDrawCreate(469.666656, 220.266647, "2~n~2~n~2~n~2~n~2~n~2~n~2~n~2~n~2~n~2");
    TextDrawLetterSize(tdWarResult[11], 0.156332, 0.857478);
    TextDrawAlignment(tdWarResult[11], 1);
    TextDrawColor(tdWarResult[11], -1);
    TextDrawSetShadow(tdWarResult[11], 0);
    TextDrawSetOutline(tdWarResult[11], 1);
    TextDrawBackgroundColor(tdWarResult[11], 51);
    TextDrawFont(tdWarResult[11], 1);
    TextDrawSetProportional(tdWarResult[11], 1);

    // Tim 2 damage
    tdWarResult[12] = TextDrawCreate(491.999969, 220.266647, "3~n~3~n~3~n~3~n~3~n~3~n~3~n~3~n~3~n~3");
    TextDrawLetterSize(tdWarResult[12], 0.156332, 0.857478);
    TextDrawAlignment(tdWarResult[12], 1);
    TextDrawColor(tdWarResult[12], -1);
    TextDrawSetShadow(tdWarResult[12], 0);
    TextDrawSetOutline(tdWarResult[12], 1);
    TextDrawBackgroundColor(tdWarResult[12], 51);
    TextDrawFont(tdWarResult[12], 1);
    TextDrawSetProportional(tdWarResult[12], 1);

    tdWarResult[13] = TextDrawCreate(518.666687, 312.611083, "usebox");
    TextDrawLetterSize(tdWarResult[13], 0.000000, -0.163990);
    TextDrawTextSize(tdWarResult[13], 124.000000, 0.000000);
    TextDrawAlignment(tdWarResult[13], 1);
    TextDrawColor(tdWarResult[13], 0);
    TextDrawUseBox(tdWarResult[13], true);
    TextDrawBoxColor(tdWarResult[13], -1);
    TextDrawSetShadow(tdWarResult[13], 0);
    TextDrawSetOutline(tdWarResult[13], 0);
    TextDrawFont(tdWarResult[13], 0);

    tdWarResult[14] = TextDrawCreate(130.666656, 323.970336, "Najvise ubistava:~n~Najmanje ubistava:~n~~n~Najvise smrti:~n~Najmanje smrti:");
    TextDrawLetterSize(tdWarResult[14], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[14], 1);
    TextDrawColor(tdWarResult[14], -1);
    TextDrawSetShadow(tdWarResult[14], 0);
    TextDrawSetOutline(tdWarResult[14], 1);
    TextDrawBackgroundColor(tdWarResult[14], 51);
    TextDrawFont(tdWarResult[14], 1);
    TextDrawSetProportional(tdWarResult[14], 1);

    // Igrac sa najvise ubistava
    tdWarResult[15] = TextDrawCreate(210.666656, 323.970336, "Frankie_Marcello");
    TextDrawLetterSize(tdWarResult[15], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[15], 1);
    TextDrawColor(tdWarResult[15], 6605055);
    TextDrawSetShadow(tdWarResult[15], 0);
    TextDrawSetOutline(tdWarResult[15], 1);
    TextDrawBackgroundColor(tdWarResult[15], 51);
    TextDrawFont(tdWarResult[15], 1);
    TextDrawSetProportional(tdWarResult[15], 1);

    // Igrac sa najmanje ubistava
    tdWarResult[16] = TextDrawCreate(210.666656, 335.470336, "Craig_Collins");
    TextDrawLetterSize(tdWarResult[16], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[16], 1);
    TextDrawColor(tdWarResult[16], -16776961);
    TextDrawSetShadow(tdWarResult[16], 0);
    TextDrawSetOutline(tdWarResult[16], 1);
    TextDrawBackgroundColor(tdWarResult[16], 51);
    TextDrawFont(tdWarResult[16], 1);
    TextDrawSetProportional(tdWarResult[16], 1);

    // Igrac sa najvise smrti
    tdWarResult[17] = TextDrawCreate(210.666656, 358.470336, "Frankie_Marcello");
    TextDrawLetterSize(tdWarResult[17], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[17], 1);
    TextDrawColor(tdWarResult[17], 6605055);
    TextDrawSetShadow(tdWarResult[17], 0);
    TextDrawSetOutline(tdWarResult[17], 1);
    TextDrawBackgroundColor(tdWarResult[17], 51);
    TextDrawFont(tdWarResult[17], 1);
    TextDrawSetProportional(tdWarResult[17], 1);

    // Igrac sa najmanje smrti
    tdWarResult[18] = TextDrawCreate(210.666656, 370.970336, "Craig_Collins");
    TextDrawLetterSize(tdWarResult[18], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[18], 1);
    TextDrawColor(tdWarResult[18], -16776961);
    TextDrawSetShadow(tdWarResult[18], 0);
    TextDrawSetOutline(tdWarResult[18], 1);
    TextDrawBackgroundColor(tdWarResult[18], 51);
    TextDrawFont(tdWarResult[18], 1);
    TextDrawSetProportional(tdWarResult[18], 1);

    tdWarResult[19] = TextDrawCreate(350.666656, 323.970336, "Najvise stete naneo:~n~Najmanje stete naneo:~n~~n~Najvise stete primio:~n~Najmanje stete primio:");
    TextDrawLetterSize(tdWarResult[19], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[19], 1);
    TextDrawColor(tdWarResult[19], -1);
    TextDrawSetShadow(tdWarResult[19], 0);
    TextDrawSetOutline(tdWarResult[19], 1);
    TextDrawBackgroundColor(tdWarResult[19], 51);
    TextDrawFont(tdWarResult[19], 1);
    TextDrawSetProportional(tdWarResult[19], 1);

    // Igrac sa najvise dmg naneto
    tdWarResult[20] = TextDrawCreate(440.666656, 323.970336, "Frankie_Marcello");
    TextDrawLetterSize(tdWarResult[20], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[20], 1);
    TextDrawColor(tdWarResult[20], 6605055);
    TextDrawSetShadow(tdWarResult[20], 0);
    TextDrawSetOutline(tdWarResult[20], 1);
    TextDrawBackgroundColor(tdWarResult[20], 51);
    TextDrawFont(tdWarResult[20], 1);
    TextDrawSetProportional(tdWarResult[20], 1);

    // Igrac sa najmanje dmg naneto
    tdWarResult[21] = TextDrawCreate(440.666656, 335.470336, "Craig_Collins");
    TextDrawLetterSize(tdWarResult[21], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[21], 1);
    TextDrawColor(tdWarResult[21], -16776961);
    TextDrawSetShadow(tdWarResult[21], 0);
    TextDrawSetOutline(tdWarResult[21], 1);
    TextDrawBackgroundColor(tdWarResult[21], 51);
    TextDrawFont(tdWarResult[21], 1);
    TextDrawSetProportional(tdWarResult[21], 1);

    // Igrac sa najvise dmg primljeno
    tdWarResult[22] = TextDrawCreate(440.666656, 358.470336, "Frankie_Marcello");
    TextDrawLetterSize(tdWarResult[22], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[22], 1);
    TextDrawColor(tdWarResult[22], 6605055);
    TextDrawSetShadow(tdWarResult[22], 0);
    TextDrawSetOutline(tdWarResult[22], 1);
    TextDrawBackgroundColor(tdWarResult[22], 51);
    TextDrawFont(tdWarResult[22], 1);
    TextDrawSetProportional(tdWarResult[22], 1);

    // Igrac sa najmanje dmg primljeno
    tdWarResult[23] = TextDrawCreate(440.666656, 370.970336, "Craig_Collins");
    TextDrawLetterSize(tdWarResult[23], 0.215994, 1.293035);
    TextDrawAlignment(tdWarResult[23], 1);
    TextDrawColor(tdWarResult[23], -16776961);
    TextDrawSetShadow(tdWarResult[23], 0);
    TextDrawSetOutline(tdWarResult[23], 1);
    TextDrawBackgroundColor(tdWarResult[23], 51);
    TextDrawFont(tdWarResult[23], 1);
    TextDrawSetProportional(tdWarResult[23], 1);

    // MVP
    tdWarResult[24] = TextDrawCreate(317.333282, 391.170379, "MVP:   Frankie Marcello");
    TextDrawLetterSize(tdWarResult[24], 0.232997, 1.442370);
    TextDrawAlignment(tdWarResult[24], 2);
    TextDrawColor(tdWarResult[24], -65281);
    TextDrawSetShadow(tdWarResult[24], 0);
    TextDrawSetOutline(tdWarResult[24], 1);
    TextDrawBackgroundColor(tdWarResult[24], 51);
    TextDrawFont(tdWarResult[24], 2);
    TextDrawSetProportional(tdWarResult[24], 1);

    // Nereseno
    tdWarResult[25] = TextDrawCreate(317.666625, 176.711120, "NERESENO");
    TextDrawLetterSize(tdWarResult[25], 0.365000, 1.898666);
    TextDrawTextSize(tdWarResult[25], 1477.999755, 111.999961);
    TextDrawAlignment(tdWarResult[25], 2);
    TextDrawColor(tdWarResult[25], -1);
    TextDrawUseBox(tdWarResult[25], true);
    TextDrawBoxColor(tdWarResult[25], -2139062017);
    TextDrawSetShadow(tdWarResult[25], 0);
    TextDrawSetOutline(tdWarResult[25], 1);
    TextDrawBackgroundColor(tdWarResult[25], 51);
    TextDrawFont(tdWarResult[25], 2);
    TextDrawSetProportional(tdWarResult[25], 1);

    // Pobednicki tim
    tdWarResult[26] = TextDrawCreate(321.666625, 176.711105, "GSF pobeda");
    TextDrawLetterSize(tdWarResult[26], 0.488997, 1.865478);
    TextDrawAlignment(tdWarResult[26], 2);
    TextDrawColor(tdWarResult[26], -5963521);
    TextDrawSetShadow(tdWarResult[26], 0);
    TextDrawSetOutline(tdWarResult[26], 1);
    TextDrawBackgroundColor(tdWarResult[26], 51);
    TextDrawFont(tdWarResult[26], 3);
    TextDrawSetProportional(tdWarResult[26], 1);

    // Pauza info
    tdWarResult[27] = TextDrawCreate(317.666625, 176.711120, "PAUZA 00:50");
    TextDrawLetterSize(tdWarResult[27], 0.365000, 1.898666);
    TextDrawTextSize(tdWarResult[27], 1477.999755, 111.999961);
    TextDrawAlignment(tdWarResult[27], 2);
    TextDrawColor(tdWarResult[27], -1);
    TextDrawUseBox(tdWarResult[27], true);
    TextDrawBoxColor(tdWarResult[27], -2139062017);
    TextDrawSetShadow(tdWarResult[27], 0);
    TextDrawSetOutline(tdWarResult[27], 1);
    TextDrawBackgroundColor(tdWarResult[27], 51);
    TextDrawFont(tdWarResult[27], 2);
    TextDrawSetProportional(tdWarResult[27], 1);