// ptdHudNfsw_Create(playerid) {

//     PlayerTD[playerid][ptdHudNfsw][0] = CreatePlayerTextDraw(playerid, 525.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][0], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][0], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][0], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][0], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][0], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][0], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][0], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][0], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][0], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][0], 520.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][1] = CreatePlayerTextDraw(playerid, 528.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][1], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][1], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][1], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][1], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][1], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][1], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][1], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][1], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][1], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][1], 523.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][2] = CreatePlayerTextDraw(playerid, 531.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][2], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][2], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][2], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][2], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][2], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][2], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][2], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][2], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][2], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][2], 526.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][3] = CreatePlayerTextDraw(playerid, 534.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][3], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][3], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][3], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][3], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][3], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][3], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][3], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][3], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][3], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][3], 529.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][4] = CreatePlayerTextDraw(playerid, 537.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][4], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][4], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][4], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][4], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][4], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][4], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][4], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][4], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][4], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][4], 532.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][5] = CreatePlayerTextDraw(playerid, 540.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][5], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][5], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][5], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][5], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][5], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][5], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][5], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][5], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][5], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][5], 535.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][6] = CreatePlayerTextDraw(playerid, 543.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][6], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][6], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][6], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][6], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][6], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][6], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][6], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][6], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][6], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][6], 538.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][7] = CreatePlayerTextDraw(playerid, 546.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][7], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][7], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][7], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][7], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][7], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][7], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][7], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][7], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][7], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][7], 541.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][8] = CreatePlayerTextDraw(playerid, 549.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][8], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][8], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][8], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][8], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][8], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][8], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][8], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][8], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][8], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][8], 544.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][9] = CreatePlayerTextDraw(playerid, 552.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][9], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][9], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][9], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][9], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][9], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][9], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][9], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][9], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][9], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][9], 547.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][10] = CreatePlayerTextDraw(playerid, 555.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][10], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][10], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][10], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][10], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][10], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][10], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][10], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][10], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][10], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][10], 550.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][11] = CreatePlayerTextDraw(playerid, 558.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][11], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][11], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][11], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][11], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][11], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][11], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][11], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][11], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][11], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][11], 553.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][12] = CreatePlayerTextDraw(playerid, 561.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][12], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][12], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][12], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][12], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][12], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][12], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][12], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][12], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][12], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][12], 556.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][13] = CreatePlayerTextDraw(playerid, 564.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][13], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][13], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][13], 0.500000, -2.400000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][13], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][13], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][13], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][13], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][13], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][13], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][13], 559.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][14] = CreatePlayerTextDraw(playerid, 567.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][14], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][14], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][14], 0.500000, -2.500000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][14], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][14], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][14], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][14], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][14], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][14], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][14], 562.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][15] = CreatePlayerTextDraw(playerid, 570.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][15], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][15], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][15], 0.500000, -2.599999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][15], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][15], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][15], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][15], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][15], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][15], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][15], 565.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][16] = CreatePlayerTextDraw(playerid, 573.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][16], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][16], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][16], 0.500000, -2.750000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][16], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][16], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][16], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][16], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][16], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][16], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][16], 568.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][17] = CreatePlayerTextDraw(playerid, 576.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][17], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][17], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][17], 0.500000, -2.900000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][17], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][17], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][17], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][17], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][17], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][17], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][17], 571.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][18] = CreatePlayerTextDraw(playerid, 579.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][18], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][18], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][18], 0.500000, -3.049999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][18], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][18], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][18], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][18], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][18], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][18], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][18], 574.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][19] = CreatePlayerTextDraw(playerid, 582.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][19], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][19], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][19], 0.500000, -3.200000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][19], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][19], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][19], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][19], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][19], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][19], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][19], 577.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][20] = CreatePlayerTextDraw(playerid, 585.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][20], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][20], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][20], 0.500000, -3.349999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][20], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][20], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][20], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][20], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][20], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][20], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][20], 580.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][21] = CreatePlayerTextDraw(playerid, 588.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][21], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][21], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][21], 0.500000, -3.450000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][21], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][21], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][21], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][21], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][21], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][21], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][21], 583.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][22] = CreatePlayerTextDraw(playerid, 591.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][22], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][22], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][22], 0.500000, -3.549999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][22], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][22], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][22], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][22], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][22], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][22], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][22], 586.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][23] = CreatePlayerTextDraw(playerid, 594.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][23], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][23], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][23], 0.500000, -3.549999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][23], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][23], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][23], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][23], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][23], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][23], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][23], 589.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][24] = CreatePlayerTextDraw(playerid, 597.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][24], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][24], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][24], 0.500000, -3.549999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][24], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][24], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][24], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][24], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][24], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][24], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][24], 592.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][25] = CreatePlayerTextDraw(playerid, 600.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][25], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][25], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][25], 0.500000, -3.549999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][25], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][25], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][25], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][25], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][25], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][25], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][25], 595.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][26] = CreatePlayerTextDraw(playerid, 603.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][26], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][26], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][26], 0.500000, -3.549999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][26], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][26], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][26], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][26], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][26], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][26], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][26], 598.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][27] = CreatePlayerTextDraw(playerid, 606.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][27], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][27], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][27], 0.500000, -3.549999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][27], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][27], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][27], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][27], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][27], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][27], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][27], 601.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][28] = CreatePlayerTextDraw(playerid, 609.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][28], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][28], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][28], 0.500000, -3.549999);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][28], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][28], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][28], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][28], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][28], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][28], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][28], 604.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][29] = CreatePlayerTextDraw(playerid, 612.000000, 412.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][29], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][29], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][29], 0.500000, -3.549998);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][29], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][29], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][29], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][29], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][29], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][29], 80);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][29], 607.000000, 0.000000);


//     ////////////////////////////////////////////
//     ///////////// IZNAD SU TARABICE ////////////
//     ////////////////////////////////////////////


//     PlayerTD[playerid][ptdHudNfsw][30] = CreatePlayerTextDraw(playerid, 628.000000, 421.000000, "_"); // vertikalni progress
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][30], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][30], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][30], 0.000000, -8.069998); // (Y; 0% = -0.3700  |  100% = -10.07)
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][30], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][30], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][30], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][30], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][30], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][30], -1124138753);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][30], 616.000000, 0.000000);

//     // PlayerTD[playerid][ptdHudNfsw][31] = CreatePlayerTextDraw(playerid, 593.000, 422.000000, "_"); // horizontalni progress (X; 0% = 503.5  |  100% = 590.8)
//     // PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][31], 255);
//     // PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][31], 1);
//     // PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][31], 0.500000, -1.099998);
//     // PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][31], -1);
//     // PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][31], 0);
//     // PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][31], 1);
//     // PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][31], 1);
//     // PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][31], 1);
//     // PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][31], 150);
//     // PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][31], 521.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][31] = CreatePlayerTextDraw(playerid, 523.500000, 422.000000, "_");
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][31], 255);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][31], 1);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][31], 0.300000, -1.099997);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][31], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][31], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][31], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][31], 1);
//     PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdHudNfsw][31], 1);
//     PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][31], 150);
//     PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][31], 588.000000, 0.000000);

//     PlayerTD[playerid][ptdHudNfsw][32] = CreatePlayerTextDraw(playerid, 593.000000, 343.000000, "000"); // Brzina kretanja
//     PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdHudNfsw][32], 3);
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][32], 120);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][32], 2);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][32], 0.579999, 4.099998);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][32], -1);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][32], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][32], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][32], 1);

//     PlayerTD[playerid][ptdHudNfsw][33] = CreatePlayerTextDraw(playerid, 607.000000, 363.000000, "?"); // Stepen prenosa
//     PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdHudNfsw][33], 2);
//     PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdHudNfsw][33], 150);
//     PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdHudNfsw][33], 2);
//     PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][33], 0.259999, 1.600000);
//     PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdHudNfsw][33], 120);
//     PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdHudNfsw][33], 0);
//     PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdHudNfsw][33], 1);
//     PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdHudNfsw][33], 0);


//     return 1;
// }

// ptdHudNfsw_Destroy(playerid) {
//     for (new i = 0; i < PTD_SIZE_HUDNFSW; i++)
//         PlayerTextDrawDestroy(playerid, PlayerTD[playerid][ptdHudNfsw][i]);
//     return 1;
// }

ptdHudNfsw_Show(playerid) {
    for (new i = 0; i < PTD_SIZE_HUDNFSW; i++)
        PlayerTextDrawShow(playerid, PlayerTD[playerid][ptdHudNfsw][i]);
    return 1;
}

ptdHudNfsw_Hide(playerid) 
{
    for (new i = 0; i < PTD_SIZE_HUDNFSW; i++)
    {
        PlayerTextDrawHide(playerid, PlayerTD[playerid][ptdHudNfsw][i]);
    }
    return 1;
}

ptdHudNfsw_UpdateSpeed(playerid, speed, topSpeed) 
{
    if (topSpeed == 0) return 1;

    new string[5];
    format(string, sizeof string, "%d", speed);
    PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][32], string);

    new Float:speedPercentage = (Float:speed * 100.0) / Float:topSpeed;

    for__loop (new i = 0; i <= floatround(speedPercentage/3.3, floatround_floor); i++) 
    {
        if (i > 29 || i < 0) break;
        PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][i], 150);
        PlayerTextDrawShow(playerid, PlayerTD[playerid][ptdHudNfsw][i]);
    }

    for__loop (new i = floatround(speedPercentage/3.3, floatround_ceil); i <= 29; i++) 
    {
        if (i > 29 || i < 0) break;
        PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][i], 80);
        PlayerTextDrawShow(playerid, PlayerTD[playerid][ptdHudNfsw][i]);
    }
    return 1;
}

ptdHudNfsw_UpdateGear(playerid, speed, topSpeed) 
{
    new gear = GetVehicleGear(playerid, speed, topSpeed);
    switch (gear) 
    {
        case GEAR_UNKNOWN:  PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "?");
        case GEAR_REVERSE:  PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "R");
        case GEAR_NEUTRAL:  PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "N");
        case GEAR_PARKING:  PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "P");
        case 1:             PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "1");
        case 2:             PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "2");
        case 3:             PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "3");
        case 4:             PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "4");
        case 5:             PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "5");
        case 6:             PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "6");
        default:            PlayerTextDrawSetString(playerid, PlayerTD[playerid][ptdHudNfsw][33], "?");
    }
    return 1;
}

ptdHudNfsw_UpdateFuel(playerid) 
{
    new vehicleid = GetPlayerVehicleID(playerid);
    if (vehicleid == INVALID_VEHICLE_ID) return 1;

    new 
        color,
        percentage = floatround(GetVehicleFuel(vehicleid) / GetVehicleTankVolume(vehicleid) * 100.0),
        Float:letterSize = -0.37 - 9.7*(GetVehicleFuel(vehicleid) / GetVehicleTankVolume(vehicleid));

    if (percentage >= 90)                           color = 0x00FF5AFF;
    else if (percentage >= 80 && percentage < 90)   color = 0x3CFF5AFF;
    else if (percentage >= 70 && percentage < 80)   color = 0x64FF5AFF;
    else if (percentage >= 60 && percentage < 70)   color = 0x82F05AFF;
    else if (percentage >= 50 && percentage < 60)   color = 0xAAF05AFF;
    else if (percentage >= 40 && percentage < 50)   color = 0xC8F05AFF;
    else if (percentage >= 30 && percentage < 40)   color = 0xE6E65AFF;
    else if (percentage >= 20 && percentage < 30)   color = 0xE6FF5AFF;
    else if (percentage >= 10 && percentage < 20)   color = 0xFADC5AFF;
    else if (percentage < 10)                       color = 0xFFBE5AFF;


    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdHudNfsw][30], 0.000000, letterSize);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdHudNfsw][30], color);
    PlayerTextDrawShow(playerid, PlayerTD[playerid][ptdHudNfsw][30]);
    return 1;
}

ptdHudNfsw_UpdateHealth(playerid) 
{
    new vehicleid = GetPlayerVehicleID(playerid);
    if (vehicleid == INVALID_VEHICLE_ID) return 1;

    new 
        Float:health,
        Float:letterSize;

    GetVehicleHealth(vehicleid, health);
    letterSize = 521.0 + 87.0*(health / 999.0);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdHudNfsw][31], letterSize, 0.000000);
    PlayerTextDrawShow(playerid, PlayerTD[playerid][ptdHudNfsw][31]);
    
    return 1;
}