ptdKatalog_Create(playerid) 
{
    PlayerTD[playerid][ptdKatalog][0] = CreatePlayerTextDraw(playerid, 120.200019, 148.003677, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][0], 0.000000, 14.350011);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][0], 520.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][0], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][0], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKatalog][0], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKatalog][0], 170);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][0], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][0], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][0], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][0], 1);

    PlayerTD[playerid][ptdKatalog][1] = CreatePlayerTextDraw(playerid, 128.866516, 128.092636, "Katalog vozila");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][1], 0.561000, 2.674370);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][1], 288.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][1], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][1], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][1], 0);
    PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdKatalog][1], 1);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][1], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][1], 0);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][1], 1);

    PlayerTD[playerid][ptdKatalog][2] = CreatePlayerTextDraw(playerid, 132.533203, 177.504104, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][2], 0.000000, 7.899996);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][2], 191.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][2], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][2], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKatalog][2], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKatalog][2], 170);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][2], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][2], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][2], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][2], 1);

    PlayerTD[playerid][ptdKatalog][3] = CreatePlayerTextDraw(playerid, 212.533203, 177.504104, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][3], 0.000000, 7.899996);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][3], 271.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][3], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][3], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKatalog][3], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKatalog][3], 170);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][3], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][3], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][3], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][3], 1);

    PlayerTD[playerid][ptdKatalog][4] = CreatePlayerTextDraw(playerid, 292.533294, 177.504104, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][4], 0.000000, 7.899996);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][4], 351.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][4], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][4], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKatalog][4], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKatalog][4], 170);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][4], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][4], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][4], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][4], 1);

    PlayerTD[playerid][ptdKatalog][5] = CreatePlayerTextDraw(playerid, 372.533294, 177.504104, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][5], 0.000000, 7.899996);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][5], 431.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][5], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][5], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKatalog][5], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKatalog][5], 170);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][5], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][5], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][5], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][5], 1);

    PlayerTD[playerid][ptdKatalog][6] = CreatePlayerTextDraw(playerid, 452.533294, 177.504104, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][6], 0.000000, 7.899996);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][6], 511.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][6], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][6], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKatalog][6], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKatalog][6], 170);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][6], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][6], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][6], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][6], 1);

    PlayerTD[playerid][ptdKatalog][7] = CreatePlayerTextDraw(playerid, 110.333343, 162.515243, "");
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][7], 90.000000, 90.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][7], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][7], -1);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][7], 0);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][7], 0);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][7], 5);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][7], 0);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][7], true);
    PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][ptdKatalog][7], 411);
    PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][ptdKatalog][7], -10.000000, 0.000000, 30.000000, 1.000000);
    PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][ptdKatalog][7], 175, 1);

    PlayerTD[playerid][ptdKatalog][8] = CreatePlayerTextDraw(playerid, 193.966567, 168.693069, "");
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][8], 90.000000, 90.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][8], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][8], -1);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][8], 0);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][8], 0);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][8], 5);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][8], 0);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][8], true);
    PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][ptdKatalog][8], 522);
    PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][ptdKatalog][8], -10.000000, 0.000000, 30.000000, 0.800000);
    PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][ptdKatalog][8], 162, 182);

    PlayerTD[playerid][ptdKatalog][9] = CreatePlayerTextDraw(playerid, 271.666687, 164.959686, "");
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][9], 90.000000, 90.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][9], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][9], -1);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][9], 0);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][9], 0);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][9], 5);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][9], 0);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][9], true);
    PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][ptdKatalog][9], 510);
    PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][ptdKatalog][9], -10.000000, 0.000000, 30.000000, 0.800000);
    PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][ptdKatalog][9], 128, 128);

    PlayerTD[playerid][ptdKatalog][10] = CreatePlayerTextDraw(playerid, 360.633239, 173.670867, "");
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][10], 90.000000, 90.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][10], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][10], -1);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][10], 0);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][10], 0);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][10], 5);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][10], 0);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][10], true);
    PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][ptdKatalog][10], 487);
    PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][ptdKatalog][10], -20.000000, 0.000000, 50.000000, 0.800000);
    PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][ptdKatalog][10], 152, 138);

    PlayerTD[playerid][ptdKatalog][11] = CreatePlayerTextDraw(playerid, 412.666717, 162.100418, "");
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][11], 124.000000, 117.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][11], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][11], -1);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][11], 0);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][11], 0);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][11], 5);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][11], 0);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][11], true);
    PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][ptdKatalog][11], 454);
    PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][ptdKatalog][11], -10.000000, 0.000000, 30.000000, 0.500000);
    PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][ptdKatalog][11], 156, 1);

    PlayerTD[playerid][ptdKatalog][12] = CreatePlayerTextDraw(playerid, 131.599945, 256.456268, "Automobili");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][12], 0.243666, 1.429334);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][12], 189.000000, 30.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][12], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][12], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][12], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][12], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][12], 2);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][12], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][12], true);

    PlayerTD[playerid][ptdKatalog][13] = CreatePlayerTextDraw(playerid, 223.000000, 256.456268, "Motori");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][13], 0.243666, 1.429334);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][13], 260.000000, 30.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][13], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][13], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][13], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][13], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][13], 2);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][13], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][13], true);

    PlayerTD[playerid][ptdKatalog][14] = CreatePlayerTextDraw(playerid, 302.000000, 256.456268, "Bicikle");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][14], 0.243666, 1.429334);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][14], 337.000000, 30.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][14], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][14], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][14], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][14], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][14], 2);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][14], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][14], true);

    PlayerTD[playerid][ptdKatalog][15] = CreatePlayerTextDraw(playerid, 370.000000, 256.456268, "Helikopteri");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][15], 0.243666, 1.429334);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][15], 431.000000, 30.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][15], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][15], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][15], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][15], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][15], 2);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][15], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][15], true);

    PlayerTD[playerid][ptdKatalog][16] = CreatePlayerTextDraw(playerid, 460.500000, 256.456268, "Brodovi");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][16], 0.243666, 1.429334);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][16], 503.000000, 30.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][16], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][16], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][16], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][16], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][16], 2);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][16], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][16], true);

    PlayerTD[playerid][ptdKatalog][17] = CreatePlayerTextDraw(playerid, 508.500244, 147.703628, " X");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKatalog][17], 0.258666, 1.197629);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKatalog][17], 525.060058, 30.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKatalog][17], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKatalog][17], -16776961);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKatalog][17], 0);
    PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdKatalog][17], 1);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKatalog][17], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKatalog][17], 2);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKatalog][17], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKatalog][17], true);

    return 1;
}

ptdKatalog_Destroy(playerid) {
    for (new i = 0; i < PTD_SIZE_KATALOG; i++) {
        PlayerTextDrawDestroy(playerid, PlayerTD[playerid][ptdKatalog][i]);
        PlayerTD[playerid][ptdKatalog][i] = PlayerText:INVALID_TEXT_DRAW;
    }
    return 1;
}

ptdKatalog_Show(playerid) {
    for (new i = 0; i < PTD_SIZE_KATALOG; i++) {
        PlayerTextDrawShow(playerid, PlayerTD[playerid][ptdKatalog][i]);
    }
    return 1;
}