ptdKeypad_Create(playerid) {
    PlayerTD[playerid][ptdKeypad][0] = CreatePlayerTextDraw(playerid, 491.000000, 234.000000, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][0], 0.000000, 20.633352);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][0], 586.933349, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][0], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][0], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][0], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][0], 505224191);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][0], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][0], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][0], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][0], 1);

    PlayerTD[playerid][ptdKeypad][1] = CreatePlayerTextDraw(playerid, 498.000000, 283.070434, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][1], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][1], 520.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][1], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][1], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][1], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][1], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][1], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][1], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][1], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][1], 1);

    PlayerTD[playerid][ptdKeypad][2] = CreatePlayerTextDraw(playerid, 528.000000, 283.070434, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][2], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][2], 550.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][2], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][2], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][2], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][2], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][2], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][2], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][2], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][2], 1);

    PlayerTD[playerid][ptdKeypad][3] = CreatePlayerTextDraw(playerid, 558.000061, 283.070434, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][3], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][3], 580.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][3], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][3], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][3], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][3], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][3], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][3], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][3], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][3], 1);

    PlayerTD[playerid][ptdKeypad][4] = CreatePlayerTextDraw(playerid, 498.000000, 317.570495, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][4], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][4], 520.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][4], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][4], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][4], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][4], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][4], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][4], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][4], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][4], 1);

    PlayerTD[playerid][ptdKeypad][5] = CreatePlayerTextDraw(playerid, 528.000000, 317.570495, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][5], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][5], 550.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][5], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][5], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][5], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][5], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][5], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][5], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][5], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][5], 1);

    PlayerTD[playerid][ptdKeypad][6] = CreatePlayerTextDraw(playerid, 558.000061, 317.570495, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][6], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][6], 580.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][6], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][6], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][6], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][6], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][6], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][6], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][6], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][6], 1);

    PlayerTD[playerid][ptdKeypad][7] = CreatePlayerTextDraw(playerid, 498.000000, 352.570495, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][7], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][7], 520.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][7], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][7], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][7], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][7], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][7], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][7], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][7], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][7], 1);

    PlayerTD[playerid][ptdKeypad][8] = CreatePlayerTextDraw(playerid, 528.000000, 352.570495, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][8], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][8], 550.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][8], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][8], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][8], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][8], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][8], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][8], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][8], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][8], 1);

    PlayerTD[playerid][ptdKeypad][9] = CreatePlayerTextDraw(playerid, 558.000061, 352.570495, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][9], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][9], 580.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][9], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][9], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][9], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][9], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][9], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][9], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][9], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][9], 1);

    PlayerTD[playerid][ptdKeypad][10] = CreatePlayerTextDraw(playerid, 498.000000, 387.570495, "___");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][10], 0.349999, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][10], 520.000000, 20.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][10], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][10], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][10], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][10], -2147483393);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][10], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][10], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][10], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][10], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKeypad][10], true);

    PlayerTD[playerid][ptdKeypad][11] = CreatePlayerTextDraw(playerid, 528.000000, 387.570495, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][11], 0.000000, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][11], 550.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][11], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][11], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][11], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][11], 255);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][11], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][11], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][11], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][11], 1);

    PlayerTD[playerid][ptdKeypad][12] = CreatePlayerTextDraw(playerid, 558.000061, 387.570495, "___");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][12], 0.349999, 2.766669);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][12], 580.000000, 20.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][12], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][12], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][12], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][12], 8388863);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][12], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][12], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][12], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][12], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKeypad][12], true);

    PlayerTD[playerid][ptdKeypad][13] = CreatePlayerTextDraw(playerid, 498.333374, 242.548370, "box");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][13], 0.000000, 3.500002);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][13], 580.000000, 0.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][13], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][13], -1);
    PlayerTextDrawUseBox(playerid, PlayerTD[playerid][ptdKeypad][13], 1);
    PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][ptdKeypad][13], -505487769);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][13], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][13], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][13], 1);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][13], 1);

    PlayerTD[playerid][ptdKeypad][14] = CreatePlayerTextDraw(playerid, 539.000000, 243.852020, ""); // kod koji je unet
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][14], 0.566666, 3.076740);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][14], 0.000000, 10.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][14], 2);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][14], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][14], 0);
    PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdKeypad][14], 2);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][14], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][14], 2);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][14], 1);

    PlayerTD[playerid][ptdKeypad][15] = CreatePlayerTextDraw(playerid, 582.333312, 224.844497, "X");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdKeypad][15], 0.335666, 1.645629);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdKeypad][15], 592.000000, 12.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdKeypad][15], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdKeypad][15], -16776961);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdKeypad][15], 0);
    PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][ptdKeypad][15], 1);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdKeypad][15], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdKeypad][15], 2);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdKeypad][15], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdKeypad][15], true);

    PlayerTD[playerid][ptdPadNum][0] = CreatePlayerTextDraw(playerid, 529.000000, 392.000000, " 0");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][0], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][0], 549.000000, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][0], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][0], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][0], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][0], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][0], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][0], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][0], true);

    PlayerTD[playerid][ptdPadNum][1] = CreatePlayerTextDraw(playerid, 499.000000, 287.000000, " 1");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][1], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][1], 519.101440, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][1], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][1], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][1], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][1], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][1], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][1], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][1], true);

    PlayerTD[playerid][ptdPadNum][2] = CreatePlayerTextDraw(playerid, 529.000000, 287.000000, " 2");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][2], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][2], 549.000000, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][2], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][2], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][2], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][2], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][2], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][2], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][2], true);

    PlayerTD[playerid][ptdPadNum][3] = CreatePlayerTextDraw(playerid, 559.000000, 287.000000, " 3");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][3], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][3], 578.000000, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][3], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][3], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][3], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][3], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][3], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][3], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][3], true);

    PlayerTD[playerid][ptdPadNum][4] = CreatePlayerTextDraw(playerid, 499.000000, 322.000000, " 4");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][4], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][4], 519.101440, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][4], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][4], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][4], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][4], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][4], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][4], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][4], true);

    PlayerTD[playerid][ptdPadNum][5] = CreatePlayerTextDraw(playerid, 529.000000, 322.000000, " 5");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][5], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][5], 549.000000, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][5], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][5], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][5], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][5], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][5], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][5], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][5], true);

    PlayerTD[playerid][ptdPadNum][6] = CreatePlayerTextDraw(playerid, 559.000000, 322.000000, " 6");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][6], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][6], 578.000000, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][6], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][6], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][6], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][6], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][6], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][6], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][6], true);

    PlayerTD[playerid][ptdPadNum][7] = CreatePlayerTextDraw(playerid, 499.000000, 357.000000, " 7");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][7], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][7], 519.101440, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][7], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][7], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][7], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][7], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][7], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][7], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][7], true);

    PlayerTD[playerid][ptdPadNum][8] = CreatePlayerTextDraw(playerid, 529.000000, 357.000000, " 8");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][8], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][8], 549.000000, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][8], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][8], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][8], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][8], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][8], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][8], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][8], true);

    PlayerTD[playerid][ptdPadNum][9] = CreatePlayerTextDraw(playerid, 559.000000, 357.000000, " 9");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][ptdPadNum][9], 0.395666, 1.853037);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][ptdPadNum][9], 578.000000, 17.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][ptdPadNum][9], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][ptdPadNum][9], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][ptdPadNum][9], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][ptdPadNum][9], 255);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][ptdPadNum][9], 3);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][ptdPadNum][9], 1);
    PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][ptdPadNum][9], true);

    return 1;
}

ptdKeypad_Destroy(playerid)
{
    for (new i = 0; i < PTD_SIZE_KEYPAD; i++)
    {
        PlayerTextDrawDestroy(playerid, PlayerTD[playerid][ptdKeypad][i]);
        PlayerTD[playerid][ptdKeypad][i] = PlayerText:INVALID_TEXT_DRAW;
    }
    for (new i = 0; i < PTD_SIZE_PADNUM; i++)
    {
        PlayerTextDrawDestroy(playerid, PlayerTD[playerid][ptdPadNum][i]);
        PlayerTD[playerid][ptdPadNum][i] = PlayerText:INVALID_TEXT_DRAW;
    }
    return 1;
}

ptdKeypad_Show(playerid)
{
    for (new i = 0; i < PTD_SIZE_KEYPAD; i++)
    {
        if (i == 15) continue; // nema X, mora da unese pin, ne moze da zatvori keypad
        PlayerTextDrawShow(playerid, PlayerTD[playerid][ptdKeypad][i]);
    }
    for (new i = 0; i < PTD_SIZE_PADNUM; i++)
    {
        PlayerTextDrawShow(playerid, PlayerTD[playerid][ptdPadNum][i]);
    }
    return 1;
}